### ISSUE TITLE
docker启动时报错

### ISSUE THREAD

**Issue by me-snowyowl** [nocobase/nocobase#1012]
docker pull nocobase/nocobase:latest
docker pull nocobase/nocobase:main
docker pull nocobase/nocobase:0.8.0-alpha.8

以上3个镜像均出现下面的错误

nginx started
copying...
yarn run v1.22.19
$ nocobase db:auth --retry=30
Connection has been established successfully.
Done in 13.64s.
yarn run v1.22.19
$ nocobase install -s
Connection has been established successfully.
Start installing NocoBase
/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:385
        throw new Error(`${plugin} plugin already exists`);
              ^
Error: error-handler plugin already exists
    at /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:385:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:102:103)
    at _next (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:104:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Done in 3.02s.
yarn run v1.22.19
$ nocobase upgrade -S
upgrading...
/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:385
        throw new Error(`${plugin} plugin already exists`);
              ^
Error: error-handler plugin already exists
    at /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:385:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:102:103)
    at _next (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:104:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/app/nocobase/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^
Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:141:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:25:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
能否提供更详细的信息呢
什么数据库
什么版本
是安装过程中还是升级过程中，什么版本升级到什么版本

**Comment by me-snowyowl** [comment]
版本：nocobase:0.8.0-alpha.8
数据库：mysql 8
拉取镜像运行出错，上面就是查看docker的日志内容

**Comment by chenos** [comment]
mysql variable 'lower_case_table_names' must be set to '0' or '2'
