### ISSUE TITLE
紧急 所有带BelongsToMany的不能新建

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1035]
![image](https://user-images.githubusercontent.com/900786/199910321-3a3c6e9f-f5ec-4f7d-b377-a7589e58f4f7.png)

![image](https://user-images.githubusercontent.com/900786/199910419-e2df75ea-c9ae-4dad-a345-729ec4518da4.png)

Version 0.8.0-alpha.9

**Comment by hongboji** [comment]
是bug ，在同一张表是反复创建删除，已经修复，等下一个小版本就可以，或者把表删除了重新建立

**Comment by baiheinet** [comment]
我 upgrade to 0.8.0-alpha.13 了,还是不行啊

**Comment by chenos** [comment]
@baiheinet 能提供一下复现流程或者视频吗？还有请求的URL和参数等等

**Comment by baiheinet** [comment]
不知道 我能不能说清楚 我尽力吧，只要是BelongsToMany的 每次升级或者 build 都会500 Internal Server Error

然后我就删除中间表
![image](https://user-images.githubusercontent.com/900786/200098549-4f9ad9b9-de76-41f6-bcfd-5101f8de99e5.png)

重新建一遍 中间表  然后把原来的数据复制进去，这就好了 百思不得其解

**Comment by baiheinet** [comment]
还有就是本地dev好好的，发布后就不行，重新建一遍 中间表 然后把原来的数据复制进去，这就好了 。
或者发布后的 新建一遍 中间表 然后把原来的数据复制进去，这就好了 。本地dev 又不行

**Comment by baiheinet** [comment]
我 yarn pm create hello 了一下 又不行了

**Comment by baiheinet** [comment]
终于找见一点有意义的提示，希望能帮到你
![image](https://user-images.githubusercontent.com/900786/200111047-7213acc4-5759-4e22-870a-c4e34a4a0cb8.png)

![image](https://user-images.githubusercontent.com/900786/200111032-26764f14-1141-4408-9712-c195841b45b2.png)
`  App running at:
  - Local:   http://localhost:13000 (copied to clipboard)
  - Network: http://10.3.4.184:13000
Error: 
    at Query.run (D:\Github\nocobase-main\node_modules\sequelize\lib\dialects\postgres\query.js:76:25)
    at D:\Github\nocobase-main\node_modules\sequelize\lib\sequelize.js:626:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgresQueryInterface.bulkInsert (D:\Github\nocobase-main\node_modules\sequelize\lib\dialects\abstract\query-interface.js:833:21)
    at recursiveBulkCreate (D:\Github\nocobase-main\node_modules\sequelize\lib\model.js:2731:25)
    at Function.bulkCreate (D:\Github\nocobase-main\node_modules\sequelize\lib\model.js:2857:12)
    at async Promise.all (index 0)
    at BelongsToMany.set (D:\Github\nocobase-main\node_modules\sequelize\lib\associations\belongs-to-many.js:645:14) {
  name: 'SequelizeDatabaseError',
  parent: error: null value in column "createdAt" of relation "t_hcllex0ee9p" violates not-null constraint
      at Parser.parseErrorMessage (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:369:69)
      at Parser.handlePacket (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:188:21)
      at Parser.parse (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (D:\Github\nocobase-main\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 232,
    severity: 'ERROR',
    code: '23502',
    detail: 'Failing row contains (null, null, 1014, 19).',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 't_hcllex0ee9p',
    column: 'createdAt',
    dataType: undefined,
    constraint: undefined,
    file: 'execMain.c',
    line: '1883',
    routine: 'ExecConstraints',
    sql: 'INSERT INTO "t_hcllex0ee9p" ("f_7l05pl39twa","f_ftp1f6lv1t7") VALUES (1014,19) RETURNING "f_7l05pl39twa","f_ftp1f6lv1t7";',
    parameters: undefined
  },
  original: error: null value in column "createdAt" of relation "t_hcllex0ee9p" violates not-null constraint
      at Parser.parseErrorMessage (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:369:69)
      at Parser.handlePacket (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:188:21)
      at Parser.parse (D:\Github\nocobase-main\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (D:\Github\nocobase-main\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 232,
    severity: 'ERROR',
    code: '23502',
    detail: 'Failing row contains (null, null, 1014, 19).',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 't_hcllex0ee9p',
    column: 'createdAt',
    dataType: undefined,
    constraint: undefined,
    file: 'execMain.c',
    line: '1883',
    routine: 'ExecConstraints',
    sql: 'INSERT INTO "t_hcllex0ee9p" ("f_7l05pl39twa","f_ftp1f6lv1t7") VALUES (1014,19) RETURNING "f_7l05pl39twa","f_ftp1f6lv1t7";',
    parameters: undefined
  },
  sql: 'INSERT INTO "t_hcllex0ee9p" ("f_7l05pl39twa","f_ftp1f6lv1t7") VALUES (1014,19) RETURNING "f_7l05pl39twa","f_ftp1f6lv1t7";',
  parameters: undefined
}

  Error:
      at Query.run (D:\Github\nocobase-main\node_modules\sequelize\lib\dialects\postgres\query.js:76:25)
      at D:\Github\nocobase-main\node_modules\sequelize\lib\sequelize.js:626:28
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at PostgresQueryInterface.bulkInsert (D:\Github\nocobase-main\node_modules\sequelize\lib\dialects\abstract\query-interface.js:833:21)
      at recursiveBulkCreate (D:\Github\nocobase-main\node_modules\sequelize\lib\model.js:2731:25)
      at Function.bulkCreate (D:\Github\nocobase-main\node_modules\sequelize\lib\model.js:2857:12)
      at async Promise.all (index 0)
      at BelongsToMany.set (D:\Github\nocobase-main\node_modules\sequelize\lib\associations\belongs-to-many.js:645:14)
`

**Comment by baiheinet** [comment]
暂时 都是 这样解决
![image](https://user-images.githubusercontent.com/900786/200111635-fe9db4b6-87c9-4e11-b675-8849c5f62097.png)

**Comment by tommyvinny** [comment]
试试换用SQL？
