### ISSUE TITLE
升级错误，无法启动了

### ISSUE THREAD

**Issue by bioermaf** [nocobase/nocobase#1047]
$ nocobase upgrade --skip-code-update
WAIT: TypeScript compiling...
The version number before upgrade is 0.7.4-alpha.7
Clear the installed application plugins
Reload the application configuration
upgrading...
Initialize all built-in plugins
Reload the application configuration

F:\new-nocobase-app\node_modules\sequelize\src\dialects\sqlite\query.js:227
      const errForStack = new Error();
                          ^
Error:
    at Database.<anonymous> (F:\new-nocobase-app\node_modules\sequelize\src\dialects\sqlite\query.js:227:27)
    at F:\new-nocobase-app\node_modules\sequelize\src\dialects\sqlite\query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (F:\new-nocobase-app\node_modules\sequelize\src\dialects\sqlite\query.js:225:12)
    at F:\new-nocobase-app\node_modules\sequelize\src\sequelize.js:649:28
    at SQLiteQueryInterface.addColumn (F:\new-nocobase-app\node_modules\sequelize\src\dialects\abstract\query-interface.js:430:12)
    at Function.sync (F:\new-nocobase-app\node_modules\sequelize\src\model.js:1373:11)
    at Sequelize.sync (F:\new-nocobase-app\node_modules\sequelize\src\sequelize.js:824:9)
F:\new-nocobase-app\node_modules\execa\lib\error.js:60

**Comment by AydenGen** [comment]
试下，但这个操作会把数据库清空，请知晓

`yarn nocobase install -f` （This operation will clear the database!!!）
