### ISSUE TITLE
前端筛选条件选定 **公式** 字段时，报错

### ISSUE THREAD

**Issue by bonashen** [nocobase/nocobase#1063]
## Describe the bug

当前端筛选条件选定 **公式** 字段时，报错如下：

react_devtools_backend.js:4026 
        
       TypeError: Cannot read properties of undefined (reading 'expression')
    at X1 (umi.37f475d7.js:1:2879031)
    at fo (umi.37f475d7.js:1:6629182)
    at Fc (umi.37f475d7.js:1:6675854)
    at Bl (umi.37f475d7.js:1:6668543)
    at Fl (umi.37f475d7.js:1:6668468)
    at kl (umi.37f475d7.js:1:6665331)
    at umi.37f475d7.js:1:6616396
    at t.unstable_runWithPriority (umi.37f475d7.js:1:65431)
    at oi (umi.37f475d7.js:1:6616105)
    at ui (umi.37f475d7.js:1:6616341)

## Version

Version 0.8.0-alpha.13

![image](https://user-images.githubusercontent.com/178377/200796370-e9273c65-3663-4c3e-b64e-2dc5aa0cfaf1.png)

**Comment by hongboji** [comment]
确认bug ，感谢提交，后续修复
