### ISSUE TITLE
Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade

### ISSUE THREAD

**Issue by Soulballad** [nocobase/nocobase#1199]
## Describe the bug

$ nocobase install -s
Connection has been established successfully.
Done in 12.05s.
yarn run v1.22.19
$ nocobase upgrade -S
/app/nocobase/node_modules/@nocobase/server/lib/application.js:148
        return model.get('value');
                     ^

TypeError: Cannot read properties of null (reading 'get')
    at /app/nocobase/node_modules/@nocobase/server/lib/application.js:148:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/application.js:116:103)
    at _next (/app/nocobase/node_modules/@nocobase/server/lib/application.js:118:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/app/nocobase/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:141:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:25:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
nginx started
yarn run v1.22.19
$ nocobase db:auth --retry=30
Connection has been established successfully.
Done in 12.05s.
yarn run v1.22.19
$ nocobase install -s
Connection has been established successfully.
Done in 12.17s.
yarn run v1.22.19

## Version

0.8.0-alpha.13

## How To Reproduce

1. docker-compose首次安装
2. 使用mysql启动
3. 首次安装

**Comment by chenos** [comment]
推荐使用最新的 main 分支的 docker 镜像（`nocobase/nocobase:main`）安装
https://github.com/nocobase/nocobase/blob/main/docker/app-mysql/docker-compose.yml
https://docs-cn.nocobase.com/welcome/getting-started/installation/docker-compose

**Comment by Soulballad** [comment]
Uncaught SyntaxError: Unexpected token '<' (at 3.f804f3da.async.js:1:1)
umi.37f475d7.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 3 failed.
(missing: http://172.18.11.3:13000/3.f804f3da.async.js)
    at i.e (umi.37f475d7.js:1:813)
    at a (umi.37f475d7.js:1:668022)
    at dynamicImport (umi.37f475d7.js:1:4882512)
    at umi.37f475d7.js:1:119528
    at s (umi.37f475d7.js:1:3900806)
    at Generator._invoke (umi.37f475d7.js:1:3902128)
    at forEach.e.<computed> [as next] (umi.37f475d7.js:1:3901229)
    at r (umi.37f475d7.js:1:640330)
    at c (umi.37f475d7.js:1:640533)

docker可以启动成功了，页面上报错；172.18.11.3 是我虚拟机的ip

**Comment by chenos** [comment]
> Uncaught SyntaxError: Unexpected token '<' (at 3.f804f3da.async.js:1:1)
> umi.37f475d7.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 3 failed.
> (missing: http://172.18.11.3:13000/3.f804f3da.async.js)
>     at i.e (umi.37f475d7.js:1:813)
>     at a (umi.37f475d7.js:1:668022)
>     at dynamicImport (umi.37f475d7.js:1:4882512)
>     at umi.37f475d7.js:1:119528
>     at s (umi.37f475d7.js:1:3900806)
>     at Generator._invoke (umi.37f475d7.js:1:3902128)
>     at forEach.e.<computed> [as next] (umi.37f475d7.js:1:3901229)
>     at r (umi.37f475d7.js:1:640330)
>     at c (umi.37f475d7.js:1:640533)
> 
> docker可以启动成功了，页面上报错；172.18.11.3 是我虚拟机的ip

缓存问题，强制刷新一下页面

**Comment by Soulballad** [comment]
可以启动成功了
