### ISSUE TITLE
Workflow Bug when updating Users collection

### ISSUE THREAD

**Issue by rouhu** [nocobase/nocobase#1278]
## Describe the bug

Workflow failed with error
{
  "stack": "SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at $isVar (/app/nocobase/node_modules/@nocobase/plugin-users/lib/server.js:130:19)\n    at FilterParser.toSequelizeParams (/app/nocobase/node_modules/@nocobase/database/lib/filter-parser.js:171:23)\n    at OptionsParser.toSequelizeParams (/app/nocobase/node_modules/@nocobase/database/lib/options-parser.js:69:43)\n    at Repository.buildQueryOptions (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:566:27)\n    at /app/nocobase/node_modules/@nocobase/database/lib/repository.js:418:35\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:72:103)\n    at _next (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:74:194)\n    at runMicrotasks (<anonymous>)",
  "message": "Unexpected token u in JSON at position 0"
}

## Version

Version 0.8.0-alpha.13.20221219132501

## How To Reproduce

Workflow tries to update newly created user record. User creating the new record has linked ClientID collection record that should be copied to the new user record.

![image](https://user-images.githubusercontent.com/6568669/209170707-ba3d11c9-85e7-4656-ba31-3817feb70658.png)

**Comment by rouhu** [comment]
Also simple query will produce the same error.
![image](https://user-images.githubusercontent.com/6568669/209220922-5b24d169-74e9-431b-8501-3b0eacc128af.png)

**Comment by mytharcher** [comment]
Please not to use "ID is variable" --- "Current user / ID" for now. Because there is no current user in any execution of workflow till now.

The current user of execution may be add in future, but still not in short plan.

**Comment by rouhu** [comment]
ok, thanks for reply. I noticed the table column users.createdById does not get populated, is this still under development ?

**Comment by rouhu** [comment]
In the latest version 0.9.0 the field users.createdById is still not populating. Any plans for that ?

**Comment by mytharcher** [comment]
May be fixed in next minor version.

**Comment by rouhu** [comment]
Thanks, its useful as this can be used in workflows to lookup some Admin user's attributes for a new user.

**Comment by rouhu** [comment]
Also getting this error when just trying to query the Users collection in workflow. Using "Created By ID" Trigger variable from another Collection to get the user who created a record.

{
  "stack": "SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at $isVar (/app/nocobase/node_modules/@nocobase/plugin-users/lib/server.js:138:19)\n    at FilterParser.toSequelizeParams (/app/nocobase/node_modules/@nocobase/database/lib/filter-parser.js:171:23)\n    at OptionsParser.toSequelizeParams (/app/nocobase/node_modules/@nocobase/database/lib/options-parser.js:69:43)\n    at Repository.buildQueryOptions (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:607:27)\n    at /app/nocobase/node_modules/@nocobase/database/lib/repository.js:197:17\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:72:103)\n    at _next (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:74:194)\n    at runMicrotasks (<anonymous>)",
  "message": "Unexpected token u in JSON at position 0"
}

![image](https://user-images.githubusercontent.com/6568669/212752883-9a937c0d-6fdd-46f1-824a-05281cec3160.png)

**Comment by mytharcher** [comment]
`$isVar` is not supported in workflow either.

**Comment by mytharcher** [comment]
Variable component are totally changed after several versions, please upgrade and check.
