### ISSUE TITLE
Problem deleting user.

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#1335]
Hello, I'm having problem trying to delete a user.
I select the user and try to delete it, but the system reports the following error: Column 'userId' cannot be null

Error
     at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
     at /app/nocobase/node_modules/sequelize/lib/sequelize.js:314:28
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async MySQLQueryInterface.update (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:12)
     at async model.save (/app/nocobase/node_modules/sequelize/lib/model.js:2432:35)
     at async model.update (/app/nocobase/node_modules/sequelize/lib/model.js:2534:12) {
   name: 'SequelizeDatabaseError',
   parent: Error: Column 'userId' cannot be null
       at Packet.asError (/app/nocobase/node_modules/mysql2/lib/packets/packet.js:728:17)
       at Execute.execute (/app/nocobase/node_modules/mysql2/lib/commands/command.js:29:26)
       at Connection.handlePacket (/app/nocobase/node_modules/mysql2/lib/connection.js:456:32)
       at PacketParser.onPacket (/app/nocobase/node_modules/mysql2/lib/connection.js:85:12)
       at PacketParser.executeStart (/app/nocobase/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.<anonymous> (/app/nocobase/node_modules/mysql2/lib/connection.js:92:25)
       at Socket.emit (node:events:527:28)
       at Socket.emit (node:domain:475:12)
       at addChunk (node:internal/streams/readable:315:12)
       at readableAddChunk (node:internal/streams/readable:289:9) {
     code: 'ER_BAD_NULL_ERROR',
     error: 1048,
     sqlState: '23000',
     sqlMessage: "Column 'userId' cannot be null",
     sql: 'UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?',
     parameters: [ null, '2023-01-06 14:44:29', 2 ]
   },
   original: Error: Column 'userId' cannot be null
       at Packet.asError (/app/nocobase/node_modules/mysql2/lib/packets/packet.js:728:17)
       at Execute.execute (/app/nocobase/node_modules/mysql2/lib/commands/command.js:29:26)
       at Connection.handlePacket (/app/nocobase/node_modules/mysql2/lib/connection.js:456:32)
       at PacketParser.onPacket (/app/nocobase/node_modules/mysql2/lib/connection.js:85:12)
       at PacketParser.executeStart (/app/nocobase/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.<anonymous> (/app/nocobase/node_modules/mysql2/lib/connection.js:92:25)
       at Socket.emit (node:events:527:28)
       at Socket.emit (node:domain:475:12)
       at addChunk (node:internal/streams/readable:315:12)
       at readableAddChunk (node:internal/streams/readable:289:9) {
     code: 'ER_BAD_NULL_ERROR',
     error: 1048,
     sqlState: '23000',
     sqlMessage: "Column 'userId' cannot be null",
     sql: 'UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?',
     parameters: [ null, '2023-01-06 14:44:29', 2 ]
   },
   sql: 'UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?',
   parameters: [ null, '2023-01-06 14:44:29', 2 ]
}
error: Column 'userId' cannot be null {"headers":{"Access-Control-Allow-Origin":"http://172.16.253.229:13000","Access-Control-Expose-Headers":"content- disposition","vary":"Origin"},"name":"SequelizeDatabaseError","original":{"code":"ER_BAD_NULL_ERROR","errno":1048,"parameters":[null,"2023-01 -06 14:44:29",2],"sql":"UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?","sqlMessage":"Column 'userId' cannot be null","sqlState":"23000"},"parameters":[null,"2023-01-06 14:44:29",2],"parent":{"code":"ER_BAD_NULL_ERROR", "errno":1048,"parameters":[null,"2023-01-06 14:44:29",2],"sql":"UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?","sqlMessage":"Column 'userId' cannot be null","sqlState":"23000"},"reqId":"de4d0791-af34-46da-ab55-c08182fb7d18","sql" :"UPDATE `rolesUsers` SET `userId`=?,`updatedAt`=? WHERE `userId` = ?","stack":"Error\n at Query.run (/app/nocobase/node_modules/sequelize/lib/ dialects/mysql/query.js:52:25)\n at /app/nocobase/node_modules/seque lize/lib/sequelize.js:314:28\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async MySQLQueryInterface.update (/app/nocobase/node_modules/sequelize/lib/dialects/abstract /query-interface.js:355:12)\n at async model.save (/app/nocobase/node_modules/sequelize/lib/model.js:2432:35)\n at async model.update (/app/nocobase /node_modules/sequelize/lib/model.js:2534:12)","timestamp":"2023-01-06T14:44:29.027Z"}
Error
     at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
     at /app/nocobase/node_modules/sequelize/lib/sequelize.js:314:28
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async MySQLQueryInterface.update (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:12)
     at async model.save (/app/nocobase/node_modules/sequelize/lib/model.js:2432:35)
     at async model.update (/app/nocobase/node_modules/sequelize/lib/model.js:253

**Comment by chenos** [comment]
Fixed in latest version.
