### ISSUE TITLE
Docker方式安装出错

### ISSUE THREAD

**Issue by yifan925** [nocobase/nocobase#1433]
CentOS Stream 8
Linux 4.18.0-408.el8.x86_64
Python 3.6.8
pip 9.0.3
Docker version 23.0.0, build e92dd87
Docker Compose version v2.15.0
Docker方式安装出错
[root@yf-2 app-mysql]# docker-compose logs app
app-mysql-app-1  | nginx started
app-mysql-app-1  | copying...
app-mysql-app-1  | yarn run v1.22.19
app-mysql-app-1  | $ nocobase start --quickstart
app-mysql-app-1  | reconnecting... 1
app-mysql-app-1  | reconnecting... 2
app-mysql-app-1  | reconnecting... 3
app-mysql-app-1  | reconnecting... 4
app-mysql-app-1  | reconnecting... 5
app-mysql-app-1  | reconnecting... 6
app-mysql-app-1  | reconnecting... 7
app-mysql-app-1  | reconnecting... 8
app-mysql-app-1  | reconnecting... 9
app-mysql-app-1  | reconnecting... 10
app-mysql-app-1  | reconnecting... 11
app-mysql-app-1  | reconnecting... 12
app-mysql-app-1  | reconnecting... 13
app-mysql-app-1  | reconnecting... 14
app-mysql-app-1  | reconnecting... 15
app-mysql-app-1  | reconnecting... 16
app-mysql-app-1  | reconnecting... 17
app-mysql-app-1  | reconnecting... 18
app-mysql-app-1  | reconnecting... 19
app-mysql-app-1  | reconnecting... 20
app-mysql-app-1  | reconnecting... 21
app-mysql-app-1  | reconnecting... 22
app-mysql-app-1  | reconnecting... 23
app-mysql-app-1  | reconnecting... 24
app-mysql-app-1  | reconnecting... 25
app-mysql-app-1  | reconnecting... 26
app-mysql-app-1  | reconnecting... 27
app-mysql-app-1  | reconnecting... 28
app-mysql-app-1  | reconnecting... 29
app-mysql-app-1  | Connection failed, please check your database connection credentials and try again.
app-mysql-app-1  | /app/nocobase/node_modules/execa/lib/error.js:60
app-mysql-app-1  |              error = new Error(message);
app-mysql-app-1  |                      ^
app-mysql-app-1  | 
app-mysql-app-1  | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js install --ignore-installed
app-mysql-app-1  |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
app-mysql-app-1  |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
app-mysql-app-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app-mysql-app-1  |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:45:9) {
app-mysql-app-1  |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js install --ignore-installed',
app-mysql-app-1  |   command: 'node ./packages/app/server/lib/index.js install --ignore-installed',
app-mysql-app-1  |   escapedCommand: 'node "./packages/app/server/lib/index.js" install --ignore-installed',
app-mysql-app-1  |   exitCode: 1,
app-mysql-app-1  |   signal: undefined,
app-mysql-app-1  |   signalDescription: undefined,
app-mysql-app-1  |   stdout: undefined,
app-mysql-app-1  |   stderr: undefined,
app-mysql-app-1  |   failed: true,
app-mysql-app-1  |   timedOut: false,
app-mysql-app-1  |   isCanceled: false,
app-mysql-app-1  |   killed: false
app-mysql-app-1  | }
app-mysql-app-1  | error Command failed with exit code 1.
app-mysql-app-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sudongyuer** [comment]
Hi, thanks for the feedback , seems like your configuration has some wrong things, please check this document https://docs.nocobase.com/welcome/getting-started/installation/docker-compose

**Comment by sudongyuer** [comment]
If it's donesn't work , please feel free to contact us 💗

**Comment by taosiqi** [comment]
大哥 解决了没

**Comment by sudongyuer** [comment]
> 

应该是已经解决了，现在NocoBase又更新了很多东西

**Comment by jf7642132** [comment]
最新版我也碰到这个问题了！！！！！最后怎么解决的？？？
