### ISSUE TITLE
全新安装docker模式mysql数据库，初始化时报错

### ISSUE THREAD

**Issue by waylonwang** [nocobase/nocobase#1468]
yarn run v1.22.19
$ nocobase start --quickstart
Connection has been established successfully.
Start installing NocoBase
Database dialect: mysql
Initialize all built-in plugins
Reload the application configuration
Connection has been established successfully.

upgrading...
Reload the application configuration
The version number before upgrade is 0.9.0-alpha.2
warn: Cannot read properties of undefined (reading 'field') {"stack":"TypeError: Cannot read properties of undefined (reading 'field')\n    at new BelongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81:69)\n    at Function.belongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/mixin.js:43:25)\n    at BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:89:42)\n    at Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:193:13)\n    at Collection.emit (node:events:527:28)\n    at Collection.emit (node:domain:475:12)\n    at Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:240:10)\n    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:141:25\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)","timestamp":"2023-02-19T05:18:43.159Z"}
/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81
    this.sourceKeyField = this.source.rawAttributes[this.sourceKey].field || this.sourceKey;
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'field')
    at new BelongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81:69)
    at Function.belongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/mixin.js:43:25)
    at BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:89:42)
    at Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:193:13)
    at Collection.emit (node:events:527:28)
    at Collection.emit (node:domain:475:12)
    at Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:240:10)
    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:141:25
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)
/app/nocobase/node_modules/execa/lib/error.js:60
    error = new Error(message);
            ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by listener-He** [comment]
我这也是一样
