### ISSUE TITLE
create-nocobase-app 安装 0.9.1-alpha.1版本 启动报错

### ISSUE THREAD

**Issue by pangff** [nocobase/nocobase#1550]
## Desc

create-nocobase-app方式安装 0.9.1-alpha.1版本 启动报错

## Version

0.9.1-alpha.1

## How To Reproduce

```
yarn create nocobase-app my-nocobase-app -d sqlite

cd my-nocobase-app 

yarn install

yarn nocobase install --lang=zh-CN

yarn dev
```

open http://localhost:3000

## Expected behavior

正常启动

## Error Screenshots

<img width="1082" alt="WeChatc1e7e11b5ce68f8ed6a596c24d3d613e" src="https://user-images.githubusercontent.com/2368696/223635052-00c389b0-5268-4d3f-82e3-77bb42875656.png">

## Error Stack

```
info: BEGIN: GET /api/app:getLang {"reqId":"f6c54e02-ffe9-4254-8fe0-a986baa101e9","timestamp":"2023-03-08T06:07:42.707Z"}
JsonWebTokenError: invalid signature
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:133:19
    at getSecret (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:94:10)
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:42:31
    at new Promise (<anonymous>)
    at JwtService.decode (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:41:12)
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:59:54
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:22:103)
    at _next (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:24:194)
error: invalid signature {"name":"JsonWebTokenError","reqId":"f6c54e02-ffe9-4254-8fe0-a986baa101e9","stack":"JsonWebTokenError: invalid signature\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:133:19\n    at getSecret (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:90:14)\n    at Object.module.exports [as verify] (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:94:10)\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:42:31\n    at new Promise (<anonymous>)\n    at JwtService.decode (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:41:12)\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:59:54\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:22:103)\n    at _next (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:24:194)","timestamp":"2023-03-08T06:07:42.813Z"}
info: ctx permission {"can":null,"reqId":"f6c54e02-ffe9-4254-8fe0-a986baa101e9","skip":true,"timestamp":"2023-03-08T06:07:42.817Z"}
info: acl params {"reqId":"f6c54e02-ffe9-4254-8fe0-a986baa101e9","timestamp":"2023-03-08T06:07:42.818Z"}
info: acl parsedParams {"reqId":"f6c54e02-ffe9-4254-8fe0-a986baa101e9","timestamp":"2023-03-08T06:07:42.827Z"}
info: BEGIN: GET /api/app:getPlugins {"reqId":"5cbad4a0-646d-40ab-8490-77539bc900fd","timestamp":"2023-03-08T06:07:42.830Z"}
JsonWebTokenError: invalid signature
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:133:19
    at getSecret (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:94:10)
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:42:31
    at new Promise (<anonymous>)
    at JwtService.decode (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:41:12)
    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:59:54
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:22:103)
    at _next (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:24:194)
error: invalid signature {"name":"JsonWebTokenError","reqId":"5cbad4a0-646d-40ab-8490-77539bc900fd","stack":"JsonWebTokenError: invalid signature\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:133:19\n    at getSecret (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:90:14)\n    at Object.module.exports [as verify] (/Users/pangff/Downloads/my-nocobase-app/node_modules/jsonwebtoken/verify.js:94:10)\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:42:31\n    at new Promise (<anonymous>)\n    at JwtService.decode (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/jwt-service.js:41:12)\n    at /Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:59:54\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:22:103)\n    at _next (/Users/pangff/Downloads/my-nocobase-app/node_modules/@nocobase/plugin-users/lib/middlewares/parseToken.js:24:194)","timestamp":"2023-03-08T06:07:42.832Z"}
```

**Comment by mytharcher** [comment]
@pangff @MarshalW 可以再试试看。

**Comment by yottoo** [comment]
> @pangff @MarshalW 可以再试试看。

could you make a new version tag?

**Comment by MarshalW** [comment]
@mytharcher, 因为是 `yarn create nocobase-app` 方式创建项目运行的，所以得等发布新版本再测试。

**Comment by pangff** [comment]
> @pangff @MarshalW 可以再试试看。

yarn create nocobase-app 方式创建发现的问题，待新版本发布后再测试确认。

**Comment by MarshalW** [comment]
@pangff @mytharcher 更新到 `Version 0.9.1-alpha.2` ，我这边测试，问题解决了。

**Comment by pangff** [comment]
@MarshalW 也做了测试，问题已解决
