### ISSUE TITLE
docker 启动报错${name} plugin does not exist

### ISSUE THREAD

**Issue by zhuxining** [nocobase/nocobase#1690]
Attaching to app-postgres_app_1
app_1       | nginx started
app_1       | copying...
app_1       | yarn run v1.22.19
app_1       | $ nocobase start --quickstart
app_1       | Connection has been established successfully.
app_1       | Application installed
app_1       | Connection has been established successfully.
app_1       | upgrading...
app_1       | Reload the application configuration
app_1       | /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:646
app_1       |     throw new Error(`${name} plugin does not exist`);
app_1       |           ^
app_1       | 
app_1       | Error: multi-app-share-collection plugin does not exist
app_1       |     at Function.getPackageName (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:646:11)
app_1       |     at Function.resolvePlugin (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:697:30)
app_1       |     at PluginManager.addStatic (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:324:30)
app_1       |     at /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:107:27
app_1       |     at Generator.next (<anonymous>)
app_1       |     at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:30:103)
app_1       |     at _next (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:32:194)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       | /app/nocobase/node_modules/execa/lib/error.js:60
app_1       |           error = new Error(message);
app_1       |                   ^
app_1       | 
app_1       | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
app_1       |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
app_1       |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
app_1       |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
app_1       |   command: 'node ./packages/app/server/lib/index.js upgrade',
app_1       |   escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
app_1       |   exitCode: 1,
app_1       |   signal: undefined,
app_1       |   signalDescription: undefined,
app_1       |   stdout: undefined,
app_1       |   stderr: undefined,
app_1       |   failed: true,
app_1       |   timedOut: false,
app_1       |   isCanceled: false,
app_1       |   killed: false
app_1       | }
app_1       | error Command failed with exit code 1.
app_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1       | nginx started
app_1       | yarn run v1.22.19
app_1       | $ nocobase start --quickstart
app_1       | Connection has been established successfully.
app_1       | Application installed
app_1       | Connection has been established successfully.
app_1       | upgrading...
app_1       | Reload the application configuration
app_1       | /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:646
app_1       |     throw new Error(`${name} plugin does not exist`);
app_1       |           ^
app_1       | 
app_1       | Error: multi-app-share-collection plugin does not exist
app_1       |     at Function.getPackageName (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:646:11)
app_1       |     at Function.resolvePlugin (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:697:30)
app_1       |     at PluginManager.addStatic (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:324:30)
app_1       |     at /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:107:27
app_1       |     at Generator.next (<anonymous>)
app_1       |     at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:30:103)
app_1       |     at _next (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:32:194)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       | /app/nocobase/node_modules/execa/lib/error.js:60
app_1       |           error = new Error(message);
app_1       |                   ^
app_1       | 
app_1       | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
app_1       |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
app_1       |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
app_1       |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
app_1       |   command: 'node ./packages/app/server/lib/index.js upgrade',
app_1       |   escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
app_1       |   exitCode: 1,
app_1       |   signal: undefined,
app_1       |   signalDescription: undefined,
app_1       |   stdout: undefined,
app_1       |   stderr: undefined,
app_1       |   failed: true,
app_1       |   timedOut: false,
app_1       |   isCanceled: false,
app_1       |   killed: false
app_1       | }
app_1       | error Command failed with exit code 1.
app_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1       | nginx started
app_1       | yarn run v1.22.19
app_1       | $ nocobase start --quickstart
app_1       | Connection has been established successfully.
app_1       | Application installed

**Comment by zhuxining** [comment]
删除容器，重新降低到之前成功安装的[0.9.0-alpha.2]版本也报错这个插件的错


Attaching to app-postgres_app_1
app_1       | nginx started
app_1       | copying...
app_1       | yarn run v1.22.19
app_1       | $ nocobase start --quickstart
app_1       | Connection has been established successfully.
app_1       | Application installed
app_1       | Connection has been established successfully.
app_1       | upgrading...
app_1       | Reload the application configuration
app_1       | /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:629
app_1       |     throw new Error(`${name} plugin does not exist`);
app_1       |           ^
app_1       | 
app_1       | Error: formula-field plugin does not exist
app_1       |     at Function.getPackageName (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:629:11)
app_1       |     at Function.resolvePlugin (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:680:30)
app_1       |     at PluginManager.addStatic (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManager.js:324:30)
app_1       |     at /app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:104:27
app_1       |     at Generator.next (<anonymous>)
app_1       |     at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:30:103)
app_1       |     at _next (/app/nocobase/node_modules/@nocobase/server/lib/plugin-manager/PluginManagerRepository.js:32:194)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       | /app/nocobase/node_modules/execa/lib/error.js:60
app_1       |           error = new Error(message);
app_1       |                   ^
app_1       | 
app_1       | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
app_1       |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
app_1       |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
app_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1       |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
app_1       |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
app_1       |   command: 'node ./packages/app/server/lib/index.js upgrade',
app_1       |   escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
app_1       |   exitCode: 1,
app_1       |   signal: undefined,
app_1       |   signalDescription: undefined,
app_1       |   stdout: undefined,
app_1       |   stderr: undefined,
app_1       |   failed: true,
app_1       |   timedOut: false,
app_1       |   isCanceled: false,
app_1       |   killed: false
app_1       | }
app_1       | error Command failed with exit code 1.
app_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
