### ISSUE TITLE
ACL Data Scope Rending Failure

### ISSUE THREAD

**Issue by JoGosGitHub** [nocobase/nocobase#1846]
## Describe the bug

Render Failed when accessing custom data scopes (ACL -> Configure -> Action Permissions -> Configure -> Individual -> Data Scope -> Add new -> Add condition)

TypeError: Cannot read properties of undefined (reading 'x-component')
at http://localhost:13000/umi.bbcc28bd.js:1:2163385
at Array.map (<anonymous>)
at oe (http://localhost:13000/umi.bbcc28bd.js:1:2163211)
at ce (http://localhost:13000/umi.bbcc28bd.js:1:2163609)
at se (http://localhost:13000/umi.bbcc28bd.js:1:2163826)
at le (http://localhost:13000/umi.bbcc28bd.js:1:2163942)
at fo (http://localhost:13000/umi.bbcc28bd.js:1:6927189)
at Fc (http://localhost:13000/umi.bbcc28bd.js:1:6973861)
at Bs (http://localhost:13000/umi.bbcc28bd.js:1:6966550)
at Fs (http://localhost:13000/umi.bbcc28bd.js:1:6966475)

## Version

Version 0.9.2-alpha.4.20230505033143

## How To Reproduce

 
Go to ACL (/admin/settings/acl/roles) -> Configure -> Action Permissions -> Configure -> Individual -> Data Scope -> Add new -> Add condition
or
Go to ACL (/admin/settings/acl/roles) -> Configure -> Action Permissions -> Configure -> Individual -> Data Scope -> edit

## Expected behavior

Page should be rendered and the Data Scope conditions should be editable

## Screenshots
![Screenshot](https://github.com/nocobase/nocobase/assets/10085077/c7e7f1da-f4c6-4069-be3b-52de7971ea05)

## Desktop (please complete the following information)

- OS: Mac (Docker Desktop)
- Browser: Chrome

**Comment by hongboji** [comment]
This problem is not recurring, please use the latest version of the configuration, help to confirm whether the solution

**Comment by JoGosGitHub** [comment]
Problem is still occurring in Version 0.9.3-alpha.1.20230523081907

TypeError: Cannot read properties of undefined (reading 'x-component')
at http://localhost:13000/umi.2e8a1b96.js:1:2202772
at Array.map (<anonymous>)
at oe (http://localhost:13000/umi.2e8a1b96.js:1:2202598)
at ce (http://localhost:13000/umi.2e8a1b96.js:1:2202996)
at se (http://localhost:13000/umi.2e8a1b96.js:1:2203213)
at le (http://localhost:13000/umi.2e8a1b96.js:1:2203329)
at fo (http://localhost:13000/umi.2e8a1b96.js:1:6939103)
at Fc (http://localhost:13000/umi.2e8a1b96.js:1:6985775)
at Bs (http://localhost:13000/umi.2e8a1b96.js:1:6978464)
at Fs (http://localhost:13000/umi.2e8a1b96.js:1:6978389)

**Comment by rouhu** [comment]
and also same problem is still occurring in Version 0.10.0-alpha.2
