### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by Zynismus16** [nocobase/nocobase#1895]
Node 16.16.0
pm2 5.3.0
yarn 1.22.19 
npm 9.6.7

```
[BABEL] Note: The code generator has deoptimised the styling of /www/wwwroot/my-nocobase-app/node_modules/mermaid/dist/mermaid-ae477ddf.js as it exceeds the max of 500KB.
/www/wwwroot/my-nocobase-app/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command was killed with SIGKILL (Forced termination): umi build
    at makeError (/www/wwwroot/my-nocobase-app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/www/wwwroot/my-nocobase-app/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/www/wwwroot/my-nocobase-app/node_modules/@nocobase/cli/src/commands/build.js:31:9) {
  shortMessage: 'Command was killed with SIGKILL (Forced termination): umi build',
  command: 'umi build',
  escapedCommand: 'umi build',
  exitCode: undefined,
  signal: 'SIGKILL',
  signalDescription: 'Forced termination',
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chenos** [comment]
看起来是内存不足导致的
