### ISSUE TITLE
批量编辑时添加一对多关系中的字段直接崩溃

### ISSUE THREAD

**Issue by OnZeng** [nocobase/nocobase#2012]
TypeError: Cannot read properties of undefined (reading 'mode')
at http://localhost:13000/umi.js:188511:36
at http://localhost:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://localhost:13000/umi.js:156483:60)
at getAssociationAppends (http://localhost:13000/umi.js:188503:23)
at http://localhost:13000/umi.js:188558:16
at http://localhost:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://localhost:13000/umi.js:156483:60)
at getNesterAppends (http://localhost:13000/umi.js:188557:16)
at http://localhost:13000/umi.js:188519:18
at http://localhost:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://localhost:13000/umi.js:156483:60)
at getAssociationAppends (http://localhost:13000/umi.js:188503:23)
at http://localhost:13000/umi.js:188522:177
at http://localhost:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://localhost:13000/umi.js:156483:60)
at getAssociationAppends (http://localhost:13000/umi.js:188503:23)
at useAssociationNames (http://localhost:13000/umi.js:188580:25)
at FormBlockProvider (http://localhost:13000/umi.js:185166:96)
at renderWithHooks (http://localhost:13000/umi.js:673968:18)
at mountIndeterminateComponent (http://localhost:13000/umi.js:676647:13)
at beginWork (http://localhost:13000/umi.js:677761:16)
at HTMLUnknownElement.callCallback (http://localhost:13000/umi.js:659353:14)
at Object.invokeGuardedCallbackDev (http://localhost:13000/umi.js:659402:16)
at invokeGuardedCallback (http://localhost:13000/umi.js:659457:31)
at beginWork$1 (http://localhost:13000/umi.js:682368:7)
at performUnitOfWork (http://localhost:13000/umi.js:681322:12)
at workLoopSync (http://localhost:13000/umi.js:681295:22)
at performSyncWorkOnRoot (http://localhost:13000/umi.js:680921:9)
at http://localhost:13000/umi.js:670254:24
at unstable_runWithPriority (http://localhost:13000/umi.js:688886:12)
at runWithPriority$1 (http://localhost:13000/umi.js:670204:10)
at flushSyncCallbackQueueImpl (http://localhost:13000/umi.js:670249:7)
at flushSyncCallbackQueue (http://localhost:13000/umi.js:670237:3)
at discreteUpdates$1 (http://localhost:13000/umi.js:681058:7)
at discreteUpdates (http://localhost:13000/umi.js:659971:12)
at dispatchDiscreteEvent (http://localhost:13000/umi.js:663333:3)

**Comment by hongboji** [comment]
已经修复
