### ISSUE TITLE
docker方式启动nocobase，连接postgres报错

### ISSUE THREAD

**Issue by jiaolongxue** [nocobase/nocobase#206]
使用docker方式部署nocobase，并修改.env中的数据库选项，启动时提示缺少pg包
```
/nocobase/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (/nocobase/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/nocobase/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:18:24)
    at new PostgresDialect (/nocobase/app/node_modules/sequelize/lib/dialects/postgres/index.js:15:30)
    at new Sequelize (/nocobase/app/node_modules/sequelize/lib/sequelize.js:340:20)
    at new Database (/nocobase/app/node_modules/@nocobase/database/lib/database.js:152:22)
    at Object.createDatabase (/nocobase/app/node_modules/@nocobase/server/lib/helper.js:76:12)
    at new Application (/nocobase/app/node_modules/@nocobase/server/lib/application.js:84:24)
    at Object.<anonymous> (/nocobase/app/lib/apis/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by zhouyanliang** [comment]
请使用最新版本
