### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'mode')

### ISSUE THREAD

**Issue by maxmaosir** [nocobase/nocobase#2061]
新建表格，新增附件字段，设置页面，批量编辑按钮添加附件字段报错（版本：0.9.4-alpha.2）
TypeError: Cannot read properties of undefined (reading 'mode')
at http://192.168.0.204:13000/umi.js:188511:36
at http://192.168.0.204:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://192.168.0.204:13000/umi.js:156483:60)
at getAssociationAppends (http://192.168.0.204:13000/umi.js:188503:23)
at http://192.168.0.204:13000/umi.js:188558:16
at http://192.168.0.204:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://192.168.0.204:13000/umi.js:156483:60)
at getNesterAppends (http://192.168.0.204:13000/umi.js:188557:16)
at http://192.168.0.204:13000/umi.js:188519:18
at http://192.168.0.204:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://192.168.0.204:13000/umi.js:156483:60)
at getAssociationAppends (http://192.168.0.204:13000/umi.js:188503:23)
at http://192.168.0.204:13000/umi.js:188522:177
at http://192.168.0.204:13000/umi.js:156485:27
at Array.forEach (<anonymous>)
at Schema.reduceProperties (http://192.168.0.204:13000/umi.js:156483:60)
at getAssociationAppends (http://192.168.0.204:13000/umi.js:188503:23)
at useAssociationNames (http://192.168.0.204:13000/umi.js:188580:25)
at FormBlockProvider (http://192.168.0.204:13000/umi.js:185166:96)
at renderWithHooks (http://192.168.0.204:13000/umi.js:673968:18)
at mountIndeterminateComponent (http://192.168.0.204:13000/umi.js:676647:13)
at beginWork (http://192.168.0.204:13000/umi.js:677761:16)
at HTMLUnknownElement.callCallback (http://192.168.0.204:13000/umi.js:659353:14)
at Object.invokeGuardedCallbackDev (http://192.168.0.204:13000/umi.js:659402:16)
at invokeGuardedCallback (http://192.168.0.204:13000/umi.js:659457:31)
at beginWork$1 (http://192.168.0.204:13000/umi.js:682368:7)
at performUnitOfWork (http://192.168.0.204:13000/umi.js:681322:12)
at workLoopSync (http://192.168.0.204:13000/umi.js:681295:22)
at performSyncWorkOnRoot (http://192.168.0.204:13000/umi.js:680921:9)
at http://192.168.0.204:13000/umi.js:670254:24
at unstable_runWithPriority (http://192.168.0.204:13000/umi.js:688886:12)
at runWithPriority$1 (http://192.168.0.204:13000/umi.js:670204:10)
at flushSyncCallbackQueueImpl (http://192.168.0.204:13000/umi.js:670249:7)
at flushSyncCallbackQueue (http://192.168.0.204:13000/umi.js:670237:3)
at discreteUpdates$1 (http://192.168.0.204:13000/umi.js:681058:7)
at discreteUpdates (http://192.168.0.204:13000/umi.js:659971:12)
at dispatchDiscreteEvent (http://192.168.0.204:13000/umi.js:663333:3)

**Comment by hongboji** [comment]
已经修复
