### ISSUE TITLE
S3 协议下  R2 无法上传文件

### ISSUE THREAD

**Issue by aiastia** [nocobase/nocobase#2262]
## Describe the bug
 之前配置的 s3 的R2 (CF），这几天发现无法上传文件 提示  提示Internal Server Error 

但是之前的文件可以预览。

## Version
Version 0.11.0-alpha.1.20230716091039

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

## Additional context

````
error: Internal Server Error {"headers":{"Access-Control-Allow-Origin":"https://noco.***.xyz","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"reqId":"***-9aa4-***-b93d-***","stack":"InternalServerError: Internal Server Error\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at /app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:110:23\n    at Generator.throw (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:29:103)\n    at _throw (/app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:30:291)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2023-07-17T03:33:49.509Z"}
InternalServerError: Internal Server Error
    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)
    at /app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:110:23
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:29:103)
    at _throw (/app/nocobase/node_modules/@nocobase/plugin-file-manager/lib/server/actions/attachments.js:30:291)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  headers: {
    'Access-Control-Allow-Origin': 'https://noco.***.xyz',
    'Access-Control-Expose-Headers': 'content-disposition',
    vary: 'Origin'
  },
  level: 'error',
  [Symbol(level)]: 'error'
}
error: END: POST /api/t_1vclxaqis1s:create {"errors":[{"message":"Internal Server Error"}],"req":{"action":{"actionName":"create","params":{"actionName":"create","resourceName":"t_1vclxaqis1s"},"resourceName":"t_1vclxaqis1s"},"header":{"x-hostname":"noco.124678.xyz","x-locale":"zh-CN","x-role":"admin","x-timezone":"+08:00"}},"reqId":"***-9aa4-***-***-***
````

**Comment by aiastia** [comment]
Version 0.11.0-alpha.1.20230717155313
仍然有这个问题 。

**Comment by chenos** [comment]
原因是 UI 上 endpoint 没了，已修复 https://github.com/nocobase/nocobase/commit/2d8451f2dd6d79b4b38b13afab45a54261858911
