### ISSUE TITLE
不能build了 dev 没问题

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2300]
## Version

```
@nocobase/client: Transform to cjs fornocobase/packages/core/client/src/plugin-manager/context.js
@nocobase/client: Transform to cjs fornocobase/packages/core/client/src/plugin-manager/index.js
@nocobase/client: Transform to cjs fornocobase/packages/core/client/src/plugin-manager/PinnedPluginListProvider.js
TypeScript: 3 semantic errors
TypeScript: emit succeeded (with errors)
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish ( nocobase\node_modules\gulp-typescript\release\output.js:131:43)
    at nocobase\node_modules\gulp-typescript\release\output.js:66:22
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy ( nocobase\node_modules\duplexify\index.js:191:15)
    at nocobase\node_modules\duplexify\index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.16.0
 nocobase\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: nocobase-build
    at makeError ( nocobase\node_modules\execa\lib\error.js:60:11)
    at handlePromise ( nocobase\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> ( nocobase\packages\core\cli\src\commands\build.js:28:9) {
  shortMessage: 'Command failed with exit code 1: nocobase-build',
  command: 'nocobase-build',
  escapedCommand: 'nocobase-build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS nocobase> yarn dev

**Comment by baiheinet** [comment]
我错了 就是一个data 没设type
改成useRequest<{ data: any }> OK了
![image](https://github.com/nocobase/nocobase/assets/900786/3236bd4d-7b01-4ec8-9d6c-1bdfb4eb21a9)
