### ISSUE TITLE
Issue on drawers and modal inputs label rendering

### ISSUE THREAD

**Issue by ice02** [nocobase/nocobase#2335]
## Describe the bug

Hello,
Since V5 migration, it seems label in drawers and modal are not rendered anymore.
The div with class ant-formily-item-label seem to be missing (see screenshot)
Their is a JS error on browser console:
`TypeError: Cannot read properties of undefined (reading 'resource')
    at _callee$ (useRequest.js:45:1)
    at tryCatch (useRequest.js:7:1)
    at Generator.<anonymous> (useRequest.js:7:1)
    at Generator.next (useRequest.js:7:1)
    at asyncGeneratorStep (useRequest.js:8:1)
    at _next (useRequest.js:9:1)
    at useRequest.js:9:1
    at new Promise (<anonymous>)
    at Object.<anonymous> (useRequest.js:9:1)
    at Object.tempService (useRequest.js:65:1)
    at Fetch.<anonymous> (Fetch.js:76:1)
    at step (tslib.es6.mjs:147:1)
    at Object.next (tslib.es6.mjs:128:1)
    at tslib.es6.mjs:121:1
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.mjs:117:1)
    at Fetch.runAsync (Fetch.js:49:1)
    at Fetch.run (Fetch.js:128:1)
    at useRequestImplement.js:47:1
    at index.js:11:1
    at commitHookEffectListMount (react-dom.development.js:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:1)
    at commitPassiveMountEffects (react-dom.development.js:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at performSyncWorkOnRoot (react-dom.development.js:26032:1)
    at flushSyncCallbacks (react-dom.development.js:12009:1)
    at commitRootImpl (react-dom.development.js:26910:1)
    at commitRoot (react-dom.development.js:26638:1)
    at finishConcurrentRender (react-dom.development.js:25937:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25765:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at queue.<computed> (task.js:61:1)
    at run (task.js:35:1)
    at MessagePort.eventListener (task.js:46:1)`

## Version

NocoBase version 0.11.1-Alpha3
ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 5.1.3)
node version 16.15.1
npm version 9.8.0
yarn version 1.22.0

## How To Reproduce

On Windows

Create a new application or get fresh source code from github
Execute yarn install
Execute yarn nocobase install
Execute yarn dev
Go on collection manager
Clic on create collection > General collection

But the issue exist on all drawers and modals

## Expected behavior

Label must be rendered :)

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/9033307/2ba2b70d-b0ed-47fa-9ca8-86eb2284c2dc)

## Desktop (please complete the following information)

- OS: Windows 10/11
- Browser Chrome 114.0.5735.199 and Edge 114.0.1823.79 

## Additional context

With a git pull from v10 to v11 it's seem to work fine

**Comment by ice02** [comment]
Hello,
I start to correct it by my self.
Seems to be a package dependencie version issue.
By using Yarn.lock of the repo, all is working fine.
If i remove and regenerate Yarn.lock, i have the bug
