### ISSUE TITLE
nocobase 无法启动

### ISSUE THREAD

**Issue by wangze-TIM** [nocobase/nocobase#2547]
$ nocobase upgrade -S
WAIT: TypeScript compiling...
upgrading...
/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:133
          uiSchema: uiSchema.get()
                             ^

TypeError: Cannot read properties of null (reading 'get')
    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:133:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)
    at _next (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:36:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/app/nocobase/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:125:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:20:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wangze-TIM** [comment]
我这边是用docker启动的 镜像版本号nocobase/nocobase:0.7.5-alpha.1

**Comment by wangze-TIM** [comment]
数据库的版本号是mysql5.7

**Comment by wangze-TIM** [comment]
<img width="1539" alt="image" src="https://github.com/nocobase/nocobase/assets/76514558/c0b59d18-c5e8-4336-89bb-9e0e4a3fb839">

**Comment by zhouyanliang** [comment]
版本太旧

**Comment by wangze-TIM** [comment]
那我怎么处理

**Comment by wangze-TIM** [comment]
我目前需要使用这个版本 有什么办法可以启动起来
