### ISSUE TITLE
docker启动nocobase:0.7.6-alpha.2出现报错,换成0.8的版本启动正常但是页面不能正常显示

### ISSUE THREAD

**Issue by wangze-TIM** [nocobase/nocobase#2548]
nginx started
copying...
yarn run v1.22.19
$ nocobase db:auth --retry=30
Connection has been established successfully.
Done in 10.87s.
yarn run v1.22.19
$ nocobase install -s
Connection has been established successfully.
Done in 10.84s.
yarn run v1.22.19
$ nocobase upgrade -S
WAIT: TypeScript compiling...
upgrading...
/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:133
          uiSchema: uiSchema.get()
                             ^

TypeError: Cannot read properties of null (reading 'get')
    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:133:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)
    at _next (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:36:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/app/nocobase/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:125:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:20:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我这边用docker镜像[7](nocobase:0.7.6-alpha.2)的版本启动出现这种错误mysql版本号是5.7
后面使用的docker镜像8的nocobase:0.8.0-alpha.5 不会出现这种报错 但是浏览器页面上不能出来正常画面

**Comment by hongboji** [comment]
使用nocobase最新版本 ，mysql使用8的最新版本

**Comment by wangze-TIM** [comment]
我想用7的版本 我的数据还在7的版本里面

**Comment by hongboji** [comment]
nocobase支持mysql版本是>8.0.17 ,看到是在做升级，具体是nocobase从多少版本升级到多少版本 ，mysql5.7是不支持的
