### ISSUE TITLE
创建相同role name的第二个user会报数据库约束错误

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#262]
使用版本分支是：nocobase_next
数据库：sqlite3

创建第一个用户正常没有报错：

```ts
await User.repository.create({
    values: {
    email: "zhangsan@a.com",
    password: "password",
    nickname: "zhangsan",
    roles: ["member"],
    },
});
```

创建第二个用户：

```ts
await User.repository.create({
    values: {
    email: "lisi@a.com",
    password: "password",
    nickname: "lisi",
    roles: ["member"],
    },
});
```

将报错：

```
 err: Error: 
        at Database.<anonymous> (/Users/marshal/projects/demo/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
        at /Users/marshal/projects/demo/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
        at new Promise (<anonymous>)
        at Query.run (/Users/marshal/projects/demo/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
        at /Users/marshal/projects/demo/node_modules/sequelize/src/sequelize.js:643:28
        at SQLiteQueryInterface.bulkInsert (/Users/marshal/projects/demo/node_modules/sequelize/src/dialects/abstract/query-interface.js:859:21)
        at recursiveBulkCreate (/Users/marshal/projects/demo/node_modules/sequelize/src/model.js:2776:25)
        at Function.bulkCreate (/Users/marshal/projects/demo/node_modules/sequelize/src/model.js:2902:12)
        at async Promise.all (index 0)
        at BelongsToMany.set (/Users/marshal/projects/demo/node_modules/sequelize/src/associations/belongs-to-many.js:653:14) {
    name: 'SequelizeUniqueConstraintError',
    errors: [ [ValidationErrorItem] ],
    parent: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: rolesUsers.roleName] {
        errno: 19,
        code: 'SQLITE_CONSTRAINT',
        sql: "INSERT INTO `rolesUsers` (`createdAt`,`updatedAt`,`userId`,`roleName`) VALUES ('2022-04-04 14:26:38.471 +00:00','2022-04-04 14:26:38.471 +00:00',2,'member');"
    },
```

查了 rolesUsers 生成的建表语句：

```sql
CREATE TABLE `rolesUsers` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `default` TINYINT(1), `userId` INTEGER NOT NULL UNIQUE REFERENCES `users` (`id`), `roleName` VARCHAR(255) NOT NULL UNIQUE REFERENCES `roles` (`name`), PRIMARY KEY (`userId`, `roleName`))
```

可能是出在 ``roleName` VARCHAR(255) NOT NULL UNIQUE`，这里 roleName 应该不做唯一约束

另外，``userId` INTEGER NOT NULL UNIQUE` 是否也不应该唯一约束，否则 user 就只能和 role 多对一关系了

完整的测试代码：

```ts
import { Application } from "@nocobase/server";

import PluginACL from "@nocobase/plugin-acl/lib/server";
import UsersPlugin from "@nocobase/plugin-users/lib/server";
import { PluginErrorHandler } from "@nocobase/plugin-error-handler/lib/server";

class MockServer extends Application {}

describe("app test", () => {
  let app: Application;

  beforeAll(async () => {
    app = new MockServer({
      registerActions: true,
      database: {
        dialect: "sqlite",
        storage: ":memory:",
        // storage: "/tmp/tmp.sqlite",
        logging: false,
      },
      resourcer: {
        prefix: `/api`,
      },
    });

    app.plugin(UsersPlugin);
    app.plugin(PluginACL);
    app.plugin(PluginErrorHandler);

    await app.load();
    await app.install({
      sync: {
        force: true,
        alter: {
          drop: true,
        },
      },
    });
  });

  afterAll(async () => {
    await app.destroy();
  });

  it("users test", async () => {
    const User = app.db.getCollection("users");

    await User.repository.create({
      values: {
        email: "zhangsan@a.com",
        password: "password",
        nickname: "zhangsan",
        roles: ["admin"],
      },
    });

    await User.repository.create({
      values: {
        email: "lisi@a.com",
        password: "password",
        nickname: "lisi",
        roles: ["member"],
      },
    });
  });
});

```

**Comment by chareice** [comment]
你好，感谢反馈。导致这个问题是因为 sequelize 在处理 sqlite 数据看的 `sync` 时有 BUG，这里暂时的解决方法是同步的参数不要传 `alter` 选项，或者是传 `alter: {drop: false}`。

```
await app.install({
  sync: {
    force: true,
    alter: {
      drop: false,
    },
  },
});
```

**Comment by MarshalW** [comment]
谢谢，按照您的做法，我将 `alter` 部分屏蔽，问题已经得到解决。

这时生成的建表语句就没有问题了：

```sql
CREATE TABLE `rolesUsers` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `default` TINYINT(1), `userId` INTEGER NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `roleName` VARCHAR(255) NOT NULL REFERENCES `roles` (`name`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`userId`, `roleName`))
```
