### ISSUE TITLE
Error db.sync() use PostgreSQL

### ISSUE THREAD

**Issue by alexsidnenko** [nocobase/nocobase#2651]
## Describe the bug

Error when run CLI command: yarn nocobase install

## Version

latest (use Git source code)

## How To Reproduce

1. git clone https://github.com/nocobase/nocobase.git my-nocobase-app
2. cd my-nocobase-app
3. yarn install
4. Edit .env file (screenshot)
5. yarn nocobase install
6. See error

## Screenshots

<img width="475" alt="Screenshot 2023-09-14 at 21 26 19" src="https://github.com/nocobase/nocobase/assets/63589831/1e49fadd-159c-4840-8cac-789b7f35da54">

## Desktop (please complete the following information)

- OS: Ubuntu 22.10 x64 
- PostgreSQL 15.3 (Ubuntu 15.3-1.pgdg22.10+1) [e.g. chrome v102, safari]

## Additional context

LOG:
~/my-nocobase-app# yarn nocobase install
yarn run v1.22.19
$ nocobase install
WAIT: TypeScript compiling...
add app main into supervisor
Connection has been established successfully.
debug: adding plugin [nocobase]... {"app":"main","timestamp":"2023-09-14T18:17:04.026Z"}
debug: before load plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-14T18:17:04.317Z"}
debug: loading plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-14T18:17:04.390Z"}
debug: after load plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-14T18:17:04.391Z"}
debug: load locale resource {"app":"main","timestamp":"2023-09-14T18:17:04.392Z"}
debug: locale resource loaded {"app":"main","timestamp":"2023-09-14T18:17:04.416Z"}
debug: Database dialect: postgres {"app":"main","timestamp":"2023-09-14T18:17:04.417Z"}
debug: emit beforeInstall {"app":"main","timestamp":"2023-09-14T18:17:04.423Z"}
debug: start install plugins {"app":"main","timestamp":"2023-09-14T18:17:04.428Z"}
debug: call db.sync() {"app":"main","timestamp":"2023-09-14T18:17:04.430Z"}
/root/my-nocobase-app/node_modules/sequelize/lib/dialects/postgres/query.js:50
    const errForStack = new Error();
                        ^

Error
    at Query.run (/root/my-nocobase-app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at <anonymous> (/root/my-nocobase-app/node_modules/sequelize/lib/sequelize.js:315:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgresQueryInterface.createTable (/root/my-nocobase-app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:98:12)
    at Function.sync (/root/my-nocobase-app/node_modules/sequelize/lib/model.js:942:7)
    at Sequelize.sync (/root/my-nocobase-app/node_modules/sequelize/lib/sequelize.js:377:9)
    at AsyncEmitter.sync (/root/my-nocobase-app/packages/core/database/src/database.ts:652:20)
    at PluginManager.install (/root/my-nocobase-app/packages/core/server/src/plugin-manager/plugin-manager.ts:312:5)
    at AsyncEmitter.install (/root/my-nocobase-app/packages/core/server/src/application.ts:603:5)
    at Command.<anonymous> (/root/my-nocobase-app/packages/core/server/src/commands/install.ts:10:7) {
  name: 'SequelizeDatabaseError',
  parent: /root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287
          const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                   ^
  
  error: permission denied for schema public
      at Parser.parseErrorMessage (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/root/my-nocobase-app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 99,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: '28',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'aclchk.c',
    line: '3650',
    routine: 'aclcheck_error',
    sql: 'CREATE TABLE IF NOT EXISTS "migrations" ("name" VARCHAR(255) , PRIMARY KEY ("name"));',
    parameters: undefined
  },
  original: /root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287
          const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                   ^
  
  error: permission denied for schema public
      at Parser.parseErrorMessage (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/root/my-nocobase-app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 99,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: '28',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'aclchk.c',
    line: '3650',
    routine: 'aclcheck_error',
    sql: 'CREATE TABLE IF NOT EXISTS "migrations" ("name" VARCHAR(255) , PRIMARY KEY ("name"));',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS "migrations" ("name" VARCHAR(255) , PRIMARY KEY ("name"));',
  parameters: {}
}
Done in 26.43s.

**Comment by alexsidnenko** [comment]
in last step error:
~/my-nocobase-app# yarn nocobase upgrade
yarn run v1.22.19
$ nocobase upgrade
WAIT: TypeScript compiling...
add app main into supervisor
Connection has been established successfully.
debug: adding plugin [nocobase]... {"app":"main","timestamp":"2023-09-15T06:40:05.551Z"}
debug: before load plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-15T06:40:05.610Z"}
debug: loading plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-15T06:40:05.684Z"}
debug: after load plugin [PresetNocoBase]... {"app":"main","timestamp":"2023-09-15T06:40:05.685Z"}
debug: load locale resource {"app":"main","timestamp":"2023-09-15T06:40:05.686Z"}
debug: locale resource loaded {"app":"main","timestamp":"2023-09-15T06:40:05.700Z"}
upgrading...
/root/my-nocobase-app/node_modules/sequelize/lib/dialects/postgres/query.js:50
    const errForStack = new Error();
                        ^

Error
    at Query.run (/root/my-nocobase-app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at <anonymous> (/root/my-nocobase-app/node_modules/sequelize/lib/sequelize.js:315:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgresQueryInterface.select (/root/my-nocobase-app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at Function.findAll (/root/my-nocobase-app/node_modules/sequelize/lib/model.js:1140:21)
    at PluginManagerRepository.find (/root/my-nocobase-app/packages/core/database/src/repository.ts:435:14)
    at PresetNocoBase.createIfNotExists (/root/my-nocobase-app/packages/presets/nocobase/src/server/index.ts:96:26)
    at AsyncEmitter.<anonymous> (/root/my-nocobase-app/packages/presets/nocobase/src/server/index.ts:74:7)
    at AsyncEmitter.emitAsync (/root/my-nocobase-app/packages/core/utils/src/mixin/AsyncEmitter.ts:38:7)
    at AsyncEmitter.upgrade (/root/my-nocobase-app/packages/core/server/src/application.ts:620:5) {
  name: 'SequelizeDatabaseError',
  parent: /root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287
          const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                   ^
  
  error: relation "applicationPlugins" does not exist
      at Parser.parseErrorMessage (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/root/my-nocobase-app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 118,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '124',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1392',
    routine: 'parserOpenTable',
    sql: 'SELECT "id", "createdAt", "updatedAt", "name", "packageName", "version", "enabled", "installed", "builtIn", "options" FROM "applicationPlugins" AS "applicationPlugins";',
    parameters: undefined
  },
  original: /root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287
          const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                   ^
  
  error: relation "applicationPlugins" does not exist
      at Parser.parseErrorMessage (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/root/my-nocobase-app/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/root/my-nocobase-app/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 118,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '124',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1392',
    routine: 'parserOpenTable',
    sql: 'SELECT "id", "createdAt", "updatedAt", "name", "packageName", "version", "enabled", "installed", "builtIn", "options" FROM "applicationPlugins" AS "applicationPlugins";',
    parameters: undefined
  },
  sql: 'SELECT "id", "createdAt", "updatedAt", "name", "packageName", "version", "enabled", "installed", "builtIn", "options" FROM "applicationPlugins" AS "applicationPlugins";',
  parameters: {}
}
Done in 32.48s.

**Comment by alexsidnenko** [comment]
I found my mistake. I used a user who was not the owner of the database
