### ISSUE TITLE
JWT token expired and I wouldn't regenerate new one

### ISSUE THREAD

**Issue by AbdelrahmanDwedar** [nocobase/nocobase#2793]
## Describe the bug

I think the JWT token is expired (it's in the log) and I don't know how to replace it with new one or make it generate a new one.

## Version

- @nocobase/devtools: `0.14.0-alpha.6`
- @nocobase/cli: `0.14.0-alpha.6`

## How To Reproduce

1. open the `localhost:13000`
2. wait till it gives an error

## Expected behavior

It should have generated a new JWT token automatically or at least have a jwt token somehwere in the `.env` file

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/67812625/580dcb77-e92d-4bda-a364-729a0a7afef4)

## Desktop (please complete the following information)

- OS: Fedora Linux 38
- Browser Brave browser beta

## Additional context

There's an error that I get when this issue appears:
```
error: jwt expired {"app":"main","expiredAt":"2023-10-08T12:58:56.000Z","name":"TokenExpiredError","reqId":"d9f37b08-8da2-4fac-b708-2ce56d716a34","stack":"TokenExpiredError: jwt expired\n    at <anonymous> (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/jsonwebtoken/verify.js:152:21)\n    at getSecret (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/jsonwebtoken/verify.js:90:14)\n    at Object.module.exports (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/jsonwebtoken/verify.js:94:10)\n    at <anonymous> (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/auth/lib/base/jwt-service.js:62:35)\n    at new Promise (<anonymous>)\n    at _JwtService2.decode (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/auth/lib/base/jwt-service.js:61:12)\n    at BasicAuth.check (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:50:51)\n    at <anonymous> (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:103:37)\n    at dataWrapping (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-wrapping.js:39:5)\n    at i18n (/home/abdelrahmandwedar/Programming/projects/web/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/i18n.js:36:3)","timestamp":"2023-10-10T12:45:22.807Z"}
```

**Comment by baiheinet** [comment]
我也遇到 怎么解
