### ISSUE TITLE
Dump/restore functionality not available

### ISSUE THREAD

**Issue by Nenzyz** [nocobase/nocobase#2946]
## Describe the bug

For purpose of backup and restore I need to run command `yarn nocobase dump` from `@nocobase/plugin-duplicator`

System responds with `[unknown command](error: unknown command 'dump')`

## Version

Docker image `nocobase/nocobase:main` with image ID `bc52e0fa2d79` 

## How To Reproduce

1. Start `nocobase/nocobase:main` image
2. Open container console
3. Enter command 

## Expected behavior

According to the documentation I expect dump and restore commands to work to be able to save and recover configuration.

Reference: https://github.com/nocobase/nocobase/tree/main/packages/plugins/%40nocobase/plugin-duplicator

## Screenshots

No

## Desktop (please complete the following information)

- OS: macOS
- Browser Safari

## Smartphone (please complete the following information)

No

## Additional context

The whole command output:
```
# yarn nocobase dump
yarn run v1.22.19
$ nocobase dump
Not handle by ipc server
error: unknown command 'dump'
(Did you mean umi?)
{
  error: CommanderError: error: unknown command 'dump'
  (Did you mean umi?)
      at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
      at _AppCommand.error (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1591:10)
      at _AppCommand.unknownCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1782:10)
      at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1304:14)
      at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
      at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:285:38)
      at _Gateway.run (/app/nocobase/node_modules/@nocobase/server/lib/gateway/index.js:242:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 'commander.unknownCommand',
    exitCode: 1,
    nestedError: undefined
  }
}
CommanderError: error: unknown command 'dump'
(Did you mean umi?)
    at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
    at _AppCommand.error (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1591:10)
    at _AppCommand.unknownCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1782:10)
    at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1304:14)
    at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
    at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:285:38)
    at _Gateway.run (/app/nocobase/node_modules/@nocobase/server/lib/gateway/index.js:242:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'commander.unknownCommand',
  exitCode: 1,
  nestedError: undefined
}
Done in 1.27s.
```

**Comment by zhouyanliang** [comment]
New version will be released soon.

**Comment by timpupu** [comment]
该问题是否解决了？如果是，通过更新版本解决的吗？
Has the problem been solved? By the new version?

**Comment by Nenzyz** [comment]
> 该问题是否解决了？如果是，通过更新版本解决的吗？ Has the problem been solved? By the new version?

Nope

**Comment by zhouyanliang** [comment]
https://github.com/nocobase/nocobase/discussions/3193

**Comment by hongboji** [comment]
Please use the latest version

**Comment by hongboji** [comment]
Backup recovery has been released

**Comment by Nenzyz** [comment]
@hongboji can you please give some more details, since I can see "restore" command in the help but there is no "dump" command and `yarn nocobase dump` gives the same error

Detail console output:
```
root@b1f43d689269:/app/nocobase# yarn nocobase dump
yarn run v1.22.19
$ nocobase dump
2024-01-15 21:33:02 [error] Not handle by ipc server|Error: Not handle by ipc server
    at IPCSocketServer.handleClientMessage (/app/nocobase/node_modules/@nocobase/server/lib/gateway/ipc-socket-server.js:104:15) reqId=a92e99d7-9ec0-4948-8124-348aeeaebfb5
{"level":"info","message":"add app main into supervisor","meta":{},"module":"application","submodule":"supervisor","method":"addApp","app":"main","reqId":"11dcfdbc-447d-4a48-917a-77636253c8ef","timestamp":"2024-01-15 21:33:02"}
{"level":"info","message":"load commands","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"11dcfdbc-447d-4a48-917a-77636253c8ef","timestamp":"2024-01-15 21:33:02"}
error: unknown command 'dump'
(Did you mean umi?)
CommanderError: error: unknown command 'dump'
(Did you mean umi?)
    at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
    at _AppCommand.error (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1591:10)
    at _AppCommand.unknownCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1782:10)
    at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1304:14)
    at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
    at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:417:38) {
  code: 'commander.unknownCommand',
  exitCode: 1,
  nestedError: undefined
}
Done in 1.58s.


root@b1f43d689269:/app/nocobase# yarn nocobase
yarn run v1.22.19
$ nocobase
2024-01-15 21:33:11 [error] Not handle by ipc server|Error: Not handle by ipc server
    at IPCSocketServer.handleClientMessage (/app/nocobase/node_modules/@nocobase/server/lib/gateway/ipc-socket-server.js:104:15) reqId=a3ffb6bc-328a-4643-896c-4a007f9d9f25
{"level":"info","message":"add app main into supervisor","meta":{},"module":"application","submodule":"supervisor","method":"addApp","app":"main","reqId":"d689f2be-43c2-4543-af51-ec8260392b91","timestamp":"2024-01-15 21:33:11"}
{"level":"info","message":"load commands","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"d689f2be-43c2-4543-af51-ec8260392b91","timestamp":"2024-01-15 21:33:11"}
Usage: nocobase [command] [options]

Options:
  -h, --help                         display help for command

Commands:
  db:auth [options]
  create-migration [options] <name>
  db:clean [options]
  db:sync
  install [options]
  upgrade
  pm
  restart
  stop
  destroy
  start [options]
  build [packages...]
  clean
  dev [options]
  doc [cmd]
  test [options]
  umi
  restore [options] <string>
  help [command]                     display help for command
CommanderError: (outputHelp)
    at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
    at _AppCommand.help (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:2065:10)
    at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1262:12)
    at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
    at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:417:38) {
  code: 'commander.help',
  exitCode: 1,
  nestedError: undefined
}
Done in 1.51s.```
