### ISSUE TITLE
Crash on Clicking [Block templates] in "yarn dev" mode

### ISSUE THREAD

**Issue by jackydevops** [nocobase/nocobase#3015]
## Describe the bug
I followed the steps outlined in the [NocoBase documentation](https://docs.nocobase.com/welcome/getting-started/installation/create-nocobase-app) to create my app, named "my-app." However, I've encountered a bug specifically when running the app in `yarn dev` mode.

Notably, the bug does not manifest under the following circumstances:

When I execute yarn build followed by yarn start.
When I clone the source code and set up the development environment using the instructions provided in [this guide](https://docs.nocobase.com/welcome/getting-started/installation/git-clone).

## Version

0.14.0-alpha.8

## How To Reproduce

1. `yarn create nocobase-app my-app`
2. Executed `yarn install` and `yarn nocobase install`
3. `yarn dev`
4. Open "All plugin settings"
5. Click on sidebar menu [Block templates]  (admin/settings/ui-schema-storage/block-templates)
6. App crash

## Expected Behavior:

The app should function correctly, and navigating to [Block Templates] in the yarn dev mode should not result in a crash.

## Actual Behavior:

Clicking on [Block Templates] in the yarn dev mode leads to a crash.

## Error Logs:
```
TypeError: Illegal invocation
at https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/vendors-node_modules_nocobase_preset-nocobase_client_js.async.js:595435:43
at tableSizeRefCallback (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/vendors-node_modules_nocobase_preset-nocobase_client_js.async.js:595448:5)
at imperativeHandleEffect (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:19224:5)
at commitHookEffectListMount (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:25269:26)
at commitLayoutEffectOnFiber (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:25392:15)
at commitLayoutMountEffects_complete (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:26798:9)
at commitLayoutEffects_begin (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:26784:7)
at commitLayoutEffects_begin (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:26766:11)
at commitLayoutEffects (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:26722:3)
at commitRootImpl (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:28999:5)
at commitRoot (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:28858:5)
at performSyncWorkOnRoot (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:28293:3)
at flushSyncCallbacks (https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:14234:22)
at https://turbo-system-gjgw9qqgrq6fprr-13000.app.github.dev/umi.js:27827:13
```

Checkout demo repo this bug: https://github.com/jackydevops/nocobase-report-issues/tree/main/nocobase-issue-1

**Comment by hongboji** [comment]
Bugs have been fixed, please upgrade to the latest version!
