### ISSUE TITLE
Error invalid signature at App startup

### ISSUE THREAD

**Issue by Baanor** [nocobase/nocobase#3154]
## Describe the bug

Unable to start app after pulling latest image.

## Version

v0.17.0-alpha.3

## How To Reproduce

Pull image, recreate container.

## Expected behavior

App updated

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/14046117/f64e815e-ccee-4f5d-9620-768185f321bb)

## Desktop (please complete the following information)

- OS: Win 11
- Browser: Chrome v119

## Additional context

Logs from the container:

`error: invalid signature {"app":"main","name":"JsonWebTokenError","reqId":"c54686dc-1fe9-4cea-92c0-8eda320f7f7b","stack":"JsonWebTokenError: invalid signature\n    at /app/nocobase/node_modules/jsonwebtoken/verify.js:133:19\n    at getSecret (/app/nocobase/node_modules/jsonwebtoken/verify.js:90:14)\n    at module.exports [as verify] (/app/nocobase/node_modules/jsonwebtoken/verify.js:94:10)\n    at /app/nocobase/node_modules/@nocobase/auth/lib/base/jwt-service.js:62:35\n    at new Promise (<anonymous>)\n    at _JwtService.decode (/app/nocobase/node_modules/@nocobase/auth/lib/base/jwt-service.js:61:12)\n    at BasicAuth.check (/app/nocobase/node_modules/@nocobase/auth/lib/base/auth.js:53:51)\n    at /app/nocobase/node_modules/@nocobase/auth/lib/auth-manager.js:103:37\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async dataWrapping (/app/nocobase/node_modules/@nocobase/server/lib/middlewares/data-wrapping.js:39:5)","timestamp":"2023-12-06T16:31:40.495Z"}
error: invalid signature {"app":"main","name":"JsonWebTokenError","reqId":"e17d679a-cfda-4608-b181-a4cfb04539ef","stack":"JsonWebTokenError: invalid signature\n    at /app/nocobase/node_modules/jsonwebtoken/verify.js:133:19\n    at getSecret (/app/nocobase/node_modules/jsonwebtoken/verify.js:90:14)\n    at module.exports [as verify] (/app/nocobase/node_modules/jsonwebtoken/verify.js:94:10)\n    at /app/nocobase/node_modules/@nocobase/auth/lib/base/jwt-service.js:62:35\n    at new Promise (<anonymous>)\n    at _JwtService.decode (/app/nocobase/node_modules/@nocobase/auth/lib/base/jwt-service.js:61:12)\n    at BasicAuth.check (/app/nocobase/node_modules/@nocobase/auth/lib/base/auth.js:53:51)\n    at /app/nocobase/node_modules/@nocobase/auth/lib/auth-manager.js:103:37\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async dataWrapping (/app/nocobase/node_modules/@nocobase/server/lib/middlewares/data-wrapping.js:39:5)","timestamp":"2023-12-06T16:32:09.721Z"}`

**Comment by hongboji** [comment]
Browser cache, you can try to clear the cache to solve the problem
