### ISSUE TITLE
workflow:bug 最新版workflow有bug程序启动不起来

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3191]
## Describe the bug

```
debug: load employee collection fields {"app":"main","timestamp":"2023-12-14T12:09:15.674Z"}
{
  error: TypeError: Cannot read properties of undefined (reading 'on')
      at WorkflowPlugin.toggle (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:240:15)
      at <anonymous> (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:202:14)
      at Array.forEach (<anonymous>)
      at AsyncEmitter.<anonymous> (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:201:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at AsyncEmitter.emitAsync (\packages\core\utils\src\mixin\AsyncEmitter.ts:41:7)
      at AsyncEmitter.start (\packages\core\server\src\application.ts:511:5)
      at AppCommand.<anonymous> (\packages\core\server\src\commands\start.ts:24:7)
      at AppCommand.parseAsync (\node_modules\commander\lib\command.js:935:5)
      at AsyncEmitter.runAsCLI (\packages\core\server\src\application.ts:450:23)
}
TypeError: Cannot read properties of undefined (reading 'on')
    at WorkflowPlugin.toggle (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:240:15)
    at <anonymous> (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:202:14)
    at Array.forEach (<anonymous>)
    at AsyncEmitter.<anonymous> (\packages\plugins\@nocobase\plugin-workflow\src\server\Plugin.ts:201:17)
event - [Webpack] Compiled in 41099 ms (18426 modules)
```

传统三板斧也没解决
```
yarn cache clean
rm -rf node_modules
yarn install
```

**Comment by mytharcher** [comment]
检查一下升级迁移是否正常完成？可以试试：

```shell
yarn nocobase upgrade
```
或者：

```shell
yarn nocobase migrator up
```

如果是正常完成的，可以再看看数据库的 `application_plugins` 表中有没有 `workflow-form-trigger` 的插件？

**Comment by baiheinet** [comment]
that is ok!! thanks.

**Comment by mytharcher** [comment]
> 别的感觉加载都OK ，就是不能启动

还不行么？

**Comment by baiheinet** [comment]
最终解决方案 用pnpm 就OK了
