### ISSUE TITLE
使用mysql数据库，初始化失败

### ISSUE THREAD

**Issue by chensong0310** [nocobase/nocobase#331]
当使用mysql数据库初始化系统时，会提示如下错误。使用sqlite数据库时可以正常使用。

```
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/root/baoshui/node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/root/baoshui/node_modules/sequelize/src/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/root/baoshui/node_modules/sequelize/src/dialects/sqlite/index.js:15:30)
    at new Sequelize (/root/baoshui/node_modules/sequelize/src/sequelize.js:357:20)
    at new Database (/root/baoshui/node_modules/@nocobase/database/src/database.ts:67:24)
    at ChinaRegionPlugin.<anonymous> (/root/baoshui/node_modules/@nocobase/plugin-china-region/src/server.ts:21:16)
    at Generator.next (<anonymous>)
    at /root/baoshui/node_modules/@nocobase/plugin-china-region/lib/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/baoshui/node_modules/@nocobase/plugin-china-region/lib/server.js:4:12)
error Command failed with exit code 1.
```

**Comment by chenos** [comment]
最新版已修复。文档更新了 Docker 的安装教程，如果命令安装的问题较多，可以试一试 Docker 的。
https://github.com/nocobase/nocobase#create-a-project-with-docker-recommended
