### ISSUE TITLE
scope for the data, and we set the data Variables, there is an error "Invalid Date"

### ISSUE THREAD

**Issue by jfelipesjc** [nocobase/nocobase#3426]
## Describe the bug

When we set the filter data scope for the data, and we set the data Variables, there is an error "Invalid Date "2024-01-23--3:00--3:00", this is the only way to filter the data scope for the Variables

## Version

Version 0.19.0-alpha.3

## How To Reproduce

1. Go to 'Any table, in Define the dice scope'
2. Click on 'Data variables and click on any option'
3. When Clicking Ok to Filter

## Desktop (please complete the following information)

- OS: Windows 10
- Browser Chrome

## Additional context

I believe it is just the format that is filtered, passing the fusiorario in "--3:00--3:00" as in the error mentioned above

https://github.com/nocobase/nocobase/assets/60535792/87765d9b-7610-4d91-89df-cab868afae0e

**Comment by hongboji** [comment]
1, archivo de configuración .env para habilitar el registro
DB_LOGGING=on
LOGGER_LEVEL=debug
2、La página de operación genera un error
3、Proporcionar archivos de registro en el directorio storage\logs para la solución de problemas.

**Comment by hongboji** [comment]
What browser is this?

**Comment by jfelipesjc** [comment]
Chrome

Em qui., 29 de fev. de 2024 às 11:25, hongboji ***@***.***>
escreveu:

**Comment by pehua** [comment]
I´ve same issue, https://github.com/nocobase/nocobase/discussions/3581.

**Comment by pehua** [comment]
Hello news?

I also have the same problem with filters.
It limits its use a lot in my case.

Regards

**Comment by pehua** [comment]
Hi.

I try with docker version and same issue.
This is the log for the error in docker.

2024-03-03 01:47:44 {"level":"info","message":"acl parsedParams","meta":{},"module":"t_eadfxhlv8jv","submodule":"list","method":"","app":"main","reqId":"b9d2a1d0-c593-4647-9f77-611464e7e2df","timestamp":"2024-03-03 04:47:44"}
2024-03-03 01:47:44 {"level":"error","message":"Invalid Date \"2024-03-03T00:00:00.000Z--3:00\"","meta":{"err":"Error: Invalid Date \"2024-03-03T00:00:00.000Z--3:00\"\n    at $dateBefore (/app/nocobase/node_modules/@nocobase/database/lib/operators/date.js:82:11)\n    at _FilterParser.toSequelizeParams (/app/nocobase/node_modules/@nocobase/database/lib/filter-parser.js:115:23)\n    at _AdjacencyListRepository.parseFilter (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:532:19)\n    at _AdjacencyListRepository.count (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:157:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _AdjacencyListRepository.findAndCount (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:275:19)\n    at async listWithPagination (/app/nocobase/node_modules/@nocobase/actions/lib/actions/list.js:60:25)\n    at async list (/app/nocobase/node_modules/@nocobase/actions/lib/actions/list.js:82:5)\n    at async middleware (/app/nocobase/node_modules/@nocobase/plugin-workflow-form-trigger/dist/server/FormTrigger.js:49:5)\n    at async /app/nocobase/node_modules/@nocobase/plugin-china-region/dist/server/index.js:46:9"},"module":"t_eadfxhlv8jv","submodule":"list","method":"error-handler","app":"main","reqId":"b9d2a1d0-c593-4647-9f77-611464e7e2df","timestamp":"2024-03-03 04:47:44"}

**Comment by wLk-Junior** [comment]
up

**Comment by pehua** [comment]
Same issue in discussion #1767 and #1771

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3732
