### ISSUE TITLE
No "dump" functionality in repository

### ISSUE THREAD

**Issue by Nenzyz** [nocobase/nocobase#3445]
## Describe the bug

As stated here https://github.com/nocobase/nocobase/tree/main/packages/plugins/%40nocobase/plugin-backup-restore there should be "dump" and "restore" cli command.

As per #2946 "restore" feature was restored but "dump" is not.

Neither in repository dump command is present.
https://github.com/nocobase/nocobase/tree/main/packages/plugins/%40nocobase/plugin-backup-restore/src/server/commands

## Version

Docker image `nocobase/nocobase:main` with image ID `1a0396fd67c8`

## How To Reproduce

1. Start nocobase/nocobase:main image
2. Open container console
3. Enter command

## Expected behavior

Command "dump" is present and is usable according to documentation.

## Screenshots

no

## Desktop (please complete the following information)

- OS: macOS
- Browser Safari

## Smartphone (please complete the following information)

no
## Additional context

Console error log:

```
root@b1f43d689269:/app/nocobase# yarn nocobase dump
yarn run v1.22.19
$ nocobase dump
2024-01-15 21:33:02 [error] Not handle by ipc server|Error: Not handle by ipc server
    at IPCSocketServer.handleClientMessage (/app/nocobase/node_modules/@nocobase/server/lib/gateway/ipc-socket-server.js:104:15) reqId=a92e99d7-9ec0-4948-8124-348aeeaebfb5
{"level":"info","message":"add app main into supervisor","meta":{},"module":"application","submodule":"supervisor","method":"addApp","app":"main","reqId":"11dcfdbc-447d-4a48-917a-77636253c8ef","timestamp":"2024-01-15 21:33:02"}
{"level":"info","message":"load commands","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"11dcfdbc-447d-4a48-917a-77636253c8ef","timestamp":"2024-01-15 21:33:02"}
error: unknown command 'dump'
(Did you mean umi?)
CommanderError: error: unknown command 'dump'
(Did you mean umi?)
    at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
    at _AppCommand.error (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1591:10)
    at _AppCommand.unknownCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1782:10)
    at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1304:14)
    at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
    at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:417:38) {
  code: 'commander.unknownCommand',
  exitCode: 1,
  nestedError: undefined
}
Done in 1.58s.


root@b1f43d689269:/app/nocobase# yarn nocobase
yarn run v1.22.19
$ nocobase
2024-01-15 21:33:11 [error] Not handle by ipc server|Error: Not handle by ipc server
    at IPCSocketServer.handleClientMessage (/app/nocobase/node_modules/@nocobase/server/lib/gateway/ipc-socket-server.js:104:15) reqId=a3ffb6bc-328a-4643-896c-4a007f9d9f25
{"level":"info","message":"add app main into supervisor","meta":{},"module":"application","submodule":"supervisor","method":"addApp","app":"main","reqId":"d689f2be-43c2-4543-af51-ec8260392b91","timestamp":"2024-01-15 21:33:11"}
{"level":"info","message":"load commands","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"d689f2be-43c2-4543-af51-ec8260392b91","timestamp":"2024-01-15 21:33:11"}
Usage: nocobase [command] [options]

Options:
  -h, --help                         display help for command

Commands:
  db:auth [options]
  create-migration [options] <name>
  db:clean [options]
  db:sync
  install [options]
  upgrade
  pm
  restart
  stop
  destroy
  start [options]
  build [packages...]
  clean
  dev [options]
  doc [cmd]
  test [options]
  umi
  restore [options] <string>
  help [command]                     display help for command
CommanderError: (outputHelp)
    at _AppCommand._exit (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:449:26)
    at _AppCommand.help (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:2065:10)
    at _AppCommand._parseCommand (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:1262:12)
    at _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:16)
    at _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:417:38) {
  code: 'commander.help',
  exitCode: 1,
  nestedError: undefined
}
Done in 1.51s.
```

**Comment by hongboji** [comment]
Functionality has been refactored, please use the Backup Restore function on the interface。
https://[docs.nocobase.com/manual/backup-restore/](https://docs.nocobase.com/manual/backup-restore/)
