### ISSUE TITLE
已搭建且运行了一段时间的项目yarn start报错

### ISSUE THREAD

**Issue by wxr-qd6** [nocobase/nocobase#362]
cmd提示在这里：

[0] TypeError: Cannot read properties of undefined (reading 'removeAction')
[0]     at ACLRole.revokeAction (C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\acl\src\acl-role.ts:84:14)
[0]     at model.<anonymous> (C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\src\model\RoleResourceModel.ts:20:14)
[0]     at Generator.next (<anonymous>)
[0]     at C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\lib\model\RoleResourceModel.js:8:71
[0]     at new Promise (<anonymous>)
[0]     at __awaiter (C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\lib\model\RoleResourceModel.js:4:12)
[0]     at model.revoke (C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\lib\model\RoleResourceModel.js:16:16)
[0]     at model.<anonymous> (C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\src\model\RoleResourceModel.ts:39:16)
[0]     at Generator.next (<anonymous>)
[0]     at C:\Users\Lenovo\nocobase\docker\app-mysql\my-nocobase-app\node_modules\@nocobase\plugin-acl\lib\model\RoleResourceModel.js:8:71
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[0] yarn start-server -s exited with code 1
--> Sending SIGTERM to other processes..
[1] yarn start-client exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
最新版已修复，建议升级一下，最新版 `0.7.0-alpha.32`，

### 手动升级

修改依赖的版本，类似下面这样。

packages/app/client/package.json

https://github.com/nocobase/nocobase/blob/09dfd3804e033b13f7d24426c9dfb9720dfafc75/packages/app/client/package.json#L13

packages/app/server/package.json

https://github.com/nocobase/nocobase/blob/09dfd3804e033b13f7d24426c9dfb9720dfafc75/packages/app/server/package.json#L14-L26

修改之后，终端执行

```bash
yarn install
yarn nocobase db:sync
yarn start
```

## Docker 版本

如果是 docker 版本，使用最新 docker 镜像就可以了


还不太清楚怎么操作，可以再等几天，近期我们会提供完整的升级文档。

**Comment by wxr-qd6** [comment]
感谢回复，非Docker版本修改之后可以正常启动了。Docker版本我同期也安装了但是没有使用过，刚才启动了一下，发现刚启动时也会报类似 TypeError: Cannot read properties of undefined (reading 'xxxxx') 的错误，但是稍等一会就正常了 : P)
