### ISSUE TITLE
yarn nocobase install --lang=zh-CN 报错，提示 Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by thirter** [nocobase/nocobase#391]
我使用 “通过 create-nocobase-app 创建项目” 的方式创建项目，运行 “ # 4. 安装 NocoBase： yarn nocobase install --lang=zh-CN ” 这个命令的时候遇到如下错误，似乎是我使用的mysql服务没有启动，想问下可能是什么原因导致的

我的环境：windows10系统， node 版本 v14.15.5

PS D:\region\nocobase> yarn nocobase install --lang=zh-CN
yarn run v1.22.10
$ cross-env DOTENV_CONFIG_PATH=.env ts-node-dev -r dotenv/config -r tsconfig-paths/register ./packages/app/server/src/index.ts install --lang=zh-CN
[INFO] 21:19:07 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (D:\region\nocobase\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:116:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ConnectionManager._connect (D:\region\nocobase\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:318:24)
    at D:\region\nocobase\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (D:\region\nocobase\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:280:7)
    at D:\region\nocobase\node_modules\sequelize\lib\sequelize.js:620:26
    at MySQLQueryInterface.showAllTables (D:\region\nocobase\node_modules\sequelize\lib\dialects\abstract\query-interface.js:316:24) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3306,
    fatal: true
  }
}

**Comment by chenos** [comment]
数据库启动了吗，数据库相关参数对了吗

**Comment by thirter** [comment]
确实是数据库没启动的原因，我已经换成docker启动的方式了，目前没有问题
