### ISSUE TITLE
S3 Compatible like DigitalOcean spaces or Minio Configuration

### ISSUE THREAD

**Issue by aalasolutions** [nocobase/nocobase#3915]
I need the support for S3 compatible like DO or MINIO.

Normally we can add the details in S3 configuration but when I added the details and tried to upload the file, i got following errors

```
{"level":"info","message":"request POST /api/attachments:create?attachmentField=job_categories.upload","method":"POST","path":"/api/attachments:create?attachmentField=job_categories.upload","req":{"header":{"x-role":"admin","x-hostname":"erp.aala.pk","x-timezone":"+05:00","x-locale":"en-US"}},"app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"info","message":"ctx permission","meta":{"can":{"role":"admin","resource":"attachments","action":"create","params":{"filter":{"createdById":"{{ctx.state.currentUser.id}}"}}},"skip":true},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"info","message":"acl params","meta":{"filter":{"createdById":"{{ctx.state.currentUser.id}}"}},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"info","message":"parseJsonTemplate.raw","meta":{"createdById":"{{ctx.state.currentUser.id}}"},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"info","message":"parseJsonTemplate.parsed","meta":{"createdById":2},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"info","message":"acl parsedParams","meta":{"filter":{"createdById":2}},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"error","message":"Invalid URL","stack":"TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:405:5)\n    at new URL (node:internal/url:676:13)\n    at parseUrl (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:31:894809)\n    at toEndpointV1 (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:31:788930)\n    at Object.c [as endpoint] (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:31:791068)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at async Upload.__uploadUsingPut (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/multer-s3/index.js:31:641683)\n    at async Upload.__doConcurrentUpload (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/multer-s3/index.js:31:643261)\n    at async Promise.all (index 0)","meta":{},"module":"attachments","submodule":"create","method":"","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"error","message":"Internal Server Error","meta":{"err":"InternalServerError: Internal Server Error\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at multipart (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/server/actions/attachments.js:102:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createMiddleware (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/server/actions/attachments.js:122:3)\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:276:7\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:249:7\n    at async /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:482:7\n    at async dateTemplate (/app/nocobase/node_modules/@nocobase/server/lib/middlewares/data-template.js:27:3)\n    at async parseVariables (/app/nocobase/node_modules/@nocobase/server/lib/middlewares/parse-variables.js:81:3)\n    at async app.acl.use.after (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:586:9)"},"module":"attachments","submodule":"create","method":"error-handler","app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
{"level":"error","message":"response /api/attachments:create?attachmentField=job_categories.upload","method":"POST","path":"/api/attachments:create?attachmentField=job_categories.upload","res":[{"message":"Internal Server Error"}],"action":{"actionName":"create","resourceName":"attachments","params":{"attachmentField":"job_categories.upload","resourceName":"attachments","actionName":"create","filter":{"createdById":2}}},"userId":2,"status":500,"cost":30,"app":"main","reqId":"ca733cb3-94b3-4151-90f6-ca1237a86571","timestamp":"2024-04-03 04:48:48"}
```

**Comment by yasz** [comment]
seems not work in s3 commpa mode , like minio .
