### ISSUE TITLE
Render Failed when enabling the allow add new option to a column of type record picker inside a sub table bounded to a tree collection association

### ISSUE THREAD

**Issue by CrineTech** [nocobase/nocobase#3989]
As described in the title, you can see the behavior also in the video.

https://github.com/nocobase/nocobase/assets/108331742/37711df5-c0ca-49f1-b2b6-d10a2d868dcd

This is the error message. The only way out of this that i've found is to completely delete the fault page and build it again.
> TypeError: Cannot read properties of undefined (reading 'concat')
at https://a_qhzrxerevjp.v7.demo.nocobase.com/p__index.fd1780dd.async.js:514:299
at https://a_qhzrxerevjp.v7.demo.nocobase.com/npm._at_formily.cacdd52b.async.js:100:153439
at Array.forEach (<anonymous>)
at M.reduceProperties (https://a_qhzrxerevjp.v7.demo.nocobase.com/npm._at_formily.cacdd52b.async.js:100:153388)
at https://a_qhzrxerevjp.v7.demo.nocobase.com/p__index.fd1780dd.async.js:514:239
at Array.map (<anonymous>)
at https://a_qhzrxerevjp.v7.demo.nocobase.com/p__index.fd1780dd.async.js:514:209
at Object.Wl [as useMemo] (https://a_qhzrxerevjp.v7.demo.nocobase.com/umi.5d1edd63.js:13:24751)
at y.useMemo (https://a_qhzrxerevjp.v7.demo.nocobase.com/umi.5d1edd63.js:16:19146)
at Mu (https://a_qhzrxerevjp.v7.demo.nocobase.com/p__index.fd1780dd.async.js:514:171)

## Version

Replicated on NocoBase v0.21.0-alpha.6 self hosted (docker) and NocoBase v0.21.0-alpha.6.20240408134846 online live demo

## How To Reproduce

1. Follow the steps to reproduce #3988
2. Add a many to one relationship on the Tasks collection called User pointing to Users
3. Edit the Add new form of the project page by selecting also the Tasks field for the form
4. Choose sub-table behavior for Tasks field
5. Display User, Name and Description columns inside the sub-table
6. Choose Record Picker option for the User column and enable the allow add new flag

## Expected behavior

The allow add new flag should not be displayed, as happens for regular collections (it seems that it is displayed only for tree collections association fields).

If the display of the option was intentional, then it should work without causing this issue and forcing to delete and re-build the whole page.

## Desktop (please complete the following information)

- OS: Windows 10 X64
- Browser Edge 123.0.2420.81, Firefox 124.0.2

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4086
