### ISSUE TITLE
开发环境下启动报错

### ISSUE THREAD

**Issue by thirter** [nocobase/nocobase#400]
我想在开发环境下启动nocobase以便做插件开发，但使用CLI运行开发环境遇到这个问题

我的操作步骤是：下载源代码并安装依赖之后，直接运行yarn nocobase install --lang=zh-CN，然后再yarn start

似乎是数据库没启动的问题，开发环境下如果要启动sqlite服务器是不是还需要一些配置，或者命令参数什么的

我是windows10环境，node版本v16.15.0，我的my-nocobase-app 生产环境可以正常运行

PS D:\work\region\nocobase> yarn start
yarn run v1.22.10
$ concurrently --kill-others "yarn start-server -s" "yarn start-client"
$ yarn nocobase start -s
$ cd packages/app/client && yarn start
$ cross-env DOTENV_CONFIG_PATH=.env ts-node-dev -r dotenv/config -r tsconfig-paths/register ./packages/app/server/src/index.ts start -s
$ umi dev
[0] [INFO] 22:40:18 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
[1] Browserslist: caniuse-lite is outdated. Please run:
[1] npx browserslist@latest --update-db
[1] 
[1] Why you should do it regularly:
[1] https://github.com/browserslist/browserslist#browsers-data-updating
[1] Starting the development server...
[1] i Compiling Webpack
[0] Error: Dialect needs to be explicitly supplied as of v4.0.0
[0]     at new Sequelize (D:\work\region\nocobase\node_modules\sequelize\lib\sequelize.js:288:13)  
[0]     at new Database (D:\work\region\nocobase\packages\core\database\src\database.ts:85:24)     
[0]     at createDatabase (D:\work\region\nocobase\packages\core\server\src\helper.ts:26:12)       
[0]     at new Application (D:\work\region\nocobase\packages\core\server\src\application.ts:103:29)
[0]     at D:\work\region\nocobase\packages\app\server\src\index.ts:6:15
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (D:\work\region\nocobase\packages\app\server\src\index.ts:24:58)
[0] [ERROR] 22:40:23 Error: Dialect needs to be explicitly supplied as of v4.0.0
[1] √ Webpack: Compiled successfully in 12.33s
[1]  DONE  Compiled successfully in 12329ms22:40:32
[1] 
[1] 
[1]   App running at:
[1]   - Local:   http://localhost:8000 (copied to clipboard)
[1]   - Network: http://192.168.48.1:8000
[1]  WAIT  Compiling...22:40:32
[1]
[1] i Compiling Webpack
[1] √ Webpack: Compiled successfully in 895.22ms
[1]  DONE  Compiled successfully in 896ms22:40:34
[1]
[1] node:internal/url:553
[1]   throw new ERR_INVALID_URL(input);
[1]   ^
[1]
[1] TypeError: Invalid URL
[1]     at new NodeError (node:internal/errors:372:5)
[1]     at URL.onParseError (node:internal/url:553:9)
[1]     at new URL (node:internal/url:629:5)
[1]     at new URL (node:internal/url:626:22)
[1]     at ProxyServer.onProxyRes (D:\work\region\nocobase\node_modules\@umijs\server\lib\Server\Server.js:321:38)
[1]     at ProxyServer.emit (D:\work\region\nocobase\node_modules\@umijs\deps\compiled\http-proxy-middleware\index.js:1:1673)
[1]     at ClientRequest.<anonymous> (D:\work\region\nocobase\node_modules\@umijs\deps\compiled\http-proxy-middleware\index.js:1:45461)
[1]     at ClientRequest.emit (node:events:527:28)
[1]     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
[1]     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
[1]     at Socket.socketOnData (node:_http_client:494:22)
[1]     at Socket.emit (node:events:527:28)
[1]     at addChunk (node:internal/streams/readable:315:12)
[1]     at readableAddChunk (node:internal/streams/readable:289:9)
[1]     at Socket.Readable.push (node:internal/streams/readable:228:10)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
[1]   input: 'http://127.0.0.1:undefined',
[1]   code: 'ERR_INVALID_URL'
[1] }
[1] yarn start-client exited with code 0
--> Sending SIGTERM to other processes..
[0] yarn start-server -s exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by thirter** [comment]
确实少了cp .env.example .env这一步，现在好了，多谢
