### ISSUE TITLE
执行 yarn nocobase create-plugin 报错

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#421]
**Describe the bug**

执行 yarn nocobase create-plugin 报错，无法创建plugin（packages/plugins目录下为空）

同样的问题也出现在 `yarn nocobase install --lang=zh-CN`有类似的报错，但不影响 `yarn start` 运行系统。

**Version**

使用 create-nocobase-app 安装，应该是`0.7.0-alpha.73`

为保持最新版本，也做了`yarn nocobase upgrade`

**To Reproduce**

执行命令报错：

```bash
yarn nocobase create-plugin my-plugin
yarn run v1.22.17
$ nocobase create-plugin my-plugin
WAIT: TypeScript compiling...

/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:42530
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:42530:18)
    at /Users/marshal/projects/my-nocobase-app/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/marshal/projects/my-nocobase-app/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:118278:21)
    at findSourceFile (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:118133:26)
    at processImportedModules (/Users/marshal/projects/my-nocobase-app/node_modules/typescript/lib/typescript.js:118539:25)
✨  Done in 1.25s.
```

**Expected behavior**
希望通过执行 `nocobase create-plugin my-plugin` 创建新插件代码架构。

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 (21E258)
 - zsh

**Comment by chenos** [comment]
初版的 `create-plugin` 命令加上了，不过插件脚手架的部分还不完整，包括插件开发文档也还在整理中，可以初步尝鲜体验一下，或者自行参考其他现有插件。

**Comment by chenos** [comment]
安装的问题也解决了，最新版本 `0.7.0-alpha.81`
