### ISSUE TITLE
在上传10g 的大文件，上传失败

### ISSUE THREAD

**Issue by jackerzz** [nocobase/nocobase#424]
# 在上传10g 的大文件时出现以下错误

# 错误信息
```js
🚀 NocoBase server running at: http://localhost:13000/
  Error: Parse Error
      at socketOnEnd (node:_http_server:603:22)
      at Socket.emit (node:events:532:35)
      at Socket.emit (node:domain:475:12)
      at endReadableNT (node:internal/streams/readable:1346:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
MulterError: File too large
    at abortWithCode (E:\uploadLol\nocobase\node_modules\multer\lib\make-middleware.js:79:22)
    at FileStream.<anonymous> (E:\uploadLol\nocobase\node_modules\multer\lib\make-middleware.js:141:11)
    at FileStream.emit (node:events:520:28)
    at FileStream.emit (node:domain:475:12)
    at PartStream.onData (E:\uploadLol\nocobase\node_modules\busboy\lib\types\multipart.js:220:18)
    at PartStream.emit (node:events:520:28)
    at PartStream.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at PartStream.Readable.push (node:internal/streams/readable:228:10) {
  code: 'LIMIT_FILE_SIZE',
  field: 'file',
  storageErrors: [],
  headers: {
    'Access-Control-Allow-Origin': 'http://192.168.31.32:13000',
    'Access-Control-Expose-Headers': 'content-disposition',
    vary: 'Origin'
  }
}

```

**Comment by mytharcher** [comment]
暂时限制了最大文件大小为 1GB，后面考虑可以将这个限制配置化，临时解决的话可以相关代码：

https://github.com/nocobase/nocobase/blob/main/packages/plugins/file-manager/src/constants.ts#L3

**Comment by jackerzz** [comment]
@mytharcher 感谢，已经测试通过了10g的限制
