### ISSUE TITLE
Set default sorting rules on table should allow sorting on Many-to-one relation

### ISSUE THREAD

**Issue by nikos** [nocobase/nocobase#4281]
When specifying the sort rules for an table it should also be possible to use a fields of a linked (many-to-one) relation.

<img width="257" alt="image" src="https://github.com/nocobase/nocobase/assets/31314/3cdba593-02d8-42d8-8720-2de7e627f96a">

**Comment by nikos** [comment]
As a work-around I added the date column on the many-to-one relation entity to be displayed in the table and marked it as sortable. When clicking on the header asc/desc buttons, I get the javascript error (HTTP Status 500):

```
npm.axios.f696c6e5.async.js:1 
                
       GET http://example.org/api/accreditation:list?pageSize=20&appends%5B%5D=event&appends%5B%5D=photographer&appends%5B%5D=updatedBy&page=1&sort%5B%5D=event.starttime&filter=%7B%7D 500 (Internal Server Error)

Error: Request failed with status code 500
    at p.exports (npm.axios.f696c6e5.async.js:1:6358)
    at p.exports (npm.axios.f696c6e5.async.js:1:8848)
    at XMLHttpRequest.s (npm.axios.f696c6e5.async.js:1:1012)
```
