### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by EmergeWise** [nocobase/nocobase#4379]
Hi, I am currently using Windows 11 and trying to install via docker-compose (with MySQL selected). After the Docker containers start, the MySQL service starts normally, but the NocoBase container fails to start. Here is the log:

$ node -r dotenv/config ./lib/apis/index.js
/nocobase/app/node_modules/sequelize/lib/sequelize.js:281
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/nocobase/app/node_modules/sequelize/lib/sequelize.js:281:13)
    at new Database (/nocobase/app/node_modules/@nocobase/database/lib/database.js:152:22)
    at Object.createDatabase (/nocobase/app/node_modules/@nocobase/server/lib/helper.js:76:12)
    at new Application (/nocobase/app/node_modules/@nocobase/server/lib/application.js:84:24)
    at Object.<anonymous> (/nocobase/app/lib/apis/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
yarn run v1.22.15
$ node -r dotenv/config ./lib/apis/index.js
/nocobase/app/node_modules/sequelize/lib/sequelize.js:281
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/nocobase/app/node_modules/sequelize/lib/sequelize.js:281:13)
    at new Database (/nocobase/app/node_modules/@nocobase/database/lib/database.js:152:22)
    at Object.createDatabase (/nocobase/app/node_modules/@nocobase/server/lib/helper.js:76:12)
    at new Application (/nocobase/app/node_modules/@nocobase/server/lib/application.js:84:24)
    at Object.<anonymous> (/nocobase/app/lib/apis/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

**Comment by hongboji** [comment]
https://docs.docker.com/docker-hub/download-rate-limit/
https://help.aliyun.com/zh/acr/user-guide/accelerate-the-pulls-of-docker-official-images
It is recommended that you specify the mirror version to pull, for example: v1.0.0-alpha.14

**Comment by Indrajeet911** [comment]
Request docker hub
