### ISSUE TITLE
Docker 安装 提示 Error: Dialect needs to be explicitly supplied as of v4.0.0

### ISSUE THREAD

**Issue by yaocanke** [nocobase/nocobase#4635]
使用Docker安装方式，按照在线文档的步骤，前面都正常，执行到docker-compose up -d发现只有mysql容器正常启动，app容器启动失败，通过docker logs app-mysql_app_1命令查看日志，如下：
[root@iZbp194oktlncswoi5ly5mZ app-mysql]# docker logs app-mysql_app_1
yarn run v1.22.15
$ node -r dotenv/config ./lib/apis/index.js
/nocobase/app/node_modules/sequelize/lib/sequelize.js:281
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/nocobase/app/node_modules/sequelize/lib/sequelize.js:281:13)
    at new Database (/nocobase/app/node_modules/@nocobase/database/lib/database.js:152:22)
    at Object.createDatabase (/nocobase/app/node_modules/@nocobase/server/lib/helper.js:76:12)
    at new Application (/nocobase/app/node_modules/@nocobase/server/lib/application.js:84:24)
    at Object.<anonymous> (/nocobase/app/lib/apis/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

docker版本
Docker version 25.0.1, build 29cf629

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/issues/4379

**Comment by chenos** [comment]
用了镜像加速导致的，需要换成具体的版本号，例如 

```yml
image: nocobase/nocobase:1.2.1-alpha
```

**Comment by yaocanke** [comment]
> 用了镜像加速导致的，需要换成具体的版本号，例如
> 
> ```yaml
> image: nocobase/nocobase:1.2.1-alpha
> ```

改成image: nocobase/nocobase:1.2.1-alpha后，再执行docker-compose pull命令，mysql可以正常拉取，但nocobase镜像一直提示i/o timeout
