### ISSUE TITLE
比较严重：区块错乱、引用，创建区块时报错

### ISSUE THREAD

**Issue by blackwhite084** [nocobase/nocobase#4924]
## * Describe the bug

1：第一个BUG：本来是正常的，页面用的好好的，然后开了个移动插件，然后用着用着突然区块就顺序变了
2：然后重新进行调整位置，又一晚上无事发生
3：第二个BUG：第二天少了一个区块，重新引用、复制出来，没有报错，前端也没有显示，新建一个页面来引用也无效，但是发现好像有一个幽灵区块影响布局
![image](https://github.com/user-attachments/assets/996f4bab-8dc6-4939-85e8-7fcf4bb5969a)

4：第三个BUG：在少了区块的页面里，剩下的某个区块后面添加空区块，报错如下（但前端有显示创建了新区块，刷新就没有了）
```
2024-07-22 10:45:56 [error] Cannot read properties of undefined (reading 'sort') meta={"err":"TypeError: Cannot read properties of undefined (reading 'sort')\n    at _UiSchemaRepository.insertSingleNode (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:601:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _UiSchemaRepository.insertNodes (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:807:9)\n    at async descriptor.value (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:83:16)\n    at async _UiSchemaRepository.insertBeside (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:771:27)\n    at async descriptor.value (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:83:16)\n    at async _UiSchemaRepository.insertAfterEnd (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:800:12)\n    at async descriptor.value (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:83:16)\n    at async _UiSchemaRepository.insertAdjacent (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:381:20)\n    at async descriptor.value (C:\\Users\\QQQQ\\Documents\\project\\js\\nocobase\\my-nocobase-app\\node_modules\\@nocobase\\plugin-ui-schema-storage\\dist\\server\\repository.js:75:27)"} module=uiSchemas submodule=insertAdjacent/hbbde6pbm76 method=error-handler app=main reqId=ea8bb921-3370-4de2-81ed-545f8eebc8b1 dataSourceKey=main
2024-07-22 10:45:56 [error] response /api/uiSchemas:insertAdjacent/hbbde6pbm76?position=afterEnd method=POST path=/api/uiSchemas:insertAdjacent/hbbde6pbm76?position=afterEnd res=[{"message":"Cannot read properties of undefined (reading 'sort')"}] action={"actionName":"insertAdjacent","resourceName":"uiSchemas","params":{"filterByTk":"hbbde6pbm76","position":"afterEnd","resourceName":"uiSchemas","resourceIndex":"hbbde6pbm76","actionName":"insertAdjacent","values":{"schema":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-acl-action":"articles:view","x-decorator":"DetailsBlockProvider","x-use-decorator-props":"useDetailsWithPaginationDecoratorProps","x-decorator-props":{"dataSource":"main","collection":"articles","readPretty":true,"action":"list","params":{"pageSize":1}},"x-toolbar":"BlockSchemaToolbar","x-settings":"blockSettings:detailsWithPagination","x-component":"CardItem","properties":{"mgrp0ruc1mu":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"Details","x-read-pretty":true,"x-use-component-props":"useDetailsWithPaginationProps","properties":{"nsi4d9zvfbf":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-initializer":"details:configureActions","x-component":"ActionBar","x-component-props":{"style":{"marginBottom":24}},"x-uid":"ibo3s5znike","name":"nsi4d9zvfbf","x-app-version":"1.2.22-alpha"},"grid":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"Grid","x-initializer":"details:configureFields","x-uid":"v2phd0i3joz","name":"grid","x-app-version":"1.2.22-alpha"},"pagination":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"Pagination","x-use-component-props":"useDetailsPaginationProps","x-uid":"x5ko5w7a99h","name":"pagination","x-app-version":"1.2.22-alpha"}},"x-uid":"xlb0aw99yir","name":"mgrp0ruc1mu","x-app-version":"1.2.22-alpha"}},"name":"b5t6pi5fo04","x-uid":"on2nvscyimr","x-index":1,"x-app-version":"1.2.22-alpha"},"wrap":null}}} userId=1 status=500 cost=300 app=main reqId=ea8bb921-3370-4de2-81ed-545f8eebc8b1
```

## * Environment

- NocoBase version:1.2.21，升级到22也无法引用区块

- Database type and version: mysql8 last
  

- OS:windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by zhouyanliang** [comment]
请确定用户当前角色有权限查看所有区块的数据源。
另外请用英文发布 issue，或者在 https://forum.nocobase.com/ 这里发布中文内容。

**Comment by blackwhite084** [comment]
> 请确定用户当前角色有权限查看所有区块的数据源。 另外请用英文发布 issue，或者在 https://forum.nocobase.com/ 这里发布中文内容。

是root权限
