### ISSUE TITLE
当前 main 分支启动 nocobase 报错，无法正常运行

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#516]
## Describe the bug

当前 main 分支启动 nocobase 报错，无法正常运行

## Version

main 分支

## How To Reproduce

执行如下命令：

```bash
cd /tmp
git clone https://github.com/nocobase/nocobase.git
cd nocobase
cp .env.example .env 
yarn install
yarn nocobase install --lang=zh-CN
yarn build
yarn start
```

报错为：

```
Connection has been established successfully.
2022-06-19T09:31:53: PM2 log: Launching in no daemon mode
2022-06-19T09:31:53: PM2 log: App [index:0] starting in -fork mode-
2022-06-19T09:31:53: PM2 log: App [index:0] online
Error
    at Database.<anonymous> (/private/tmp/nocobase/node_modules/sequelize/lib/dialects/sqlite/query.js:227:27)
    at /private/tmp/nocobase/node_modules/sequelize/lib/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/private/tmp/nocobase/node_modules/sequelize/lib/dialects/sqlite/query.js:225:12)
    at /private/tmp/nocobase/node_modules/sequelize/lib/sequelize.js:626:28
    at async SQLiteQueryInterface.select (/private/tmp/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
    at async Function.findAll (/private/tmp/nocobase/node_modules/sequelize/lib/model.js:1754:21) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such table: collections] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `key`, `name`, `title`, `inherit`, `options`, `sort` FROM `collections` AS `collections`;'
  },
  original: [Error: SQLITE_ERROR: no such table: collections] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `key`, `name`, `title`, `inherit`, `options`, `sort` FROM `collections` AS `collections`;'
  },
  sql: 'SELECT `key`, `name`, `title`, `inherit`, `options`, `sort` FROM `collections` AS `collections`;',
  parameters: undefined
}
```

发现 `./storage/db/nocobase.sqlite` 字节数为0

然后执行同步数据库命令：

```bash
yarn nocobase db:sync
```

再次运行，当打开浏览器访问时报错：

```
yarn run v1.22.17
$ nocobase start
Connection has been established successfully.
2022-06-19T09:32:46: PM2 log: Launching in no daemon mode
2022-06-19T09:32:47: PM2 log: App [index:0] starting in -fork mode-
2022-06-19T09:32:47: PM2 log: App [index:0] online
🚀 NocoBase server running at: http://localhost:13000/
TypeError: Cannot read properties of null (reading 'get')
    at /private/tmp/nocobase/packages/plugins/client/lib/server.js:129:54
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/private/tmp/nocobase/packages/plugins/client/lib/server.js:62:103)
    at _next (/private/tmp/nocobase/packages/plugins/client/lib/server.js:64:194)
```

## Expected behavior

希望能够按照文档次序构建并正常运行

## Desktop (please complete the following information)

- OS: macOS 12.4 (21F79)
- Browser chrome
- Version  102.0.5005.61（正式版本） (x86_64)

**Comment by chenos** [comment]
重新安装试试：

```
yarn nocobase install --lang=zh-CN -c
```

**Comment by chenos** [comment]
@MarshalW 已修复

**Comment by MarshalW** [comment]
重新 git pull 再重复之前的步骤，执行 `yarn nocobase install --lang=zh-CN -c`，问题解决了。
