### ISSUE TITLE
Building nocbase using CLI is failing at  "yarn nocobase install --lang=en-US"

### ISSUE THREAD

**Issue by MMirabito** [nocobase/nocobase#5202]
## * Describe the bug
using the following [Steps](https://docs.nocobase.com/welcome/getting-started/installation/create-nocobase-app) to install via CLI - unable to connect to Postgres DB

When executing `yarn nocobase install --lang=en-US`

`5432","timezone":"-04:00","underscored":false,"migrator":{"context":{"app":{"appName":"main","name":"main"}}},"logger":{}} meta={"databaseInstanceId":"H-YdRDT_A6l4y0IAcXVJ4"} module=database app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [info]  add app main into supervisor                 module=application submodule=supervisor method=addApp app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  attempt 1/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  will retry in 50ms...                        module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  attempt 2/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  will retry in 100ms...                       module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  attempt 3/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  will retry in 200ms...                       module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  attempt 4/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:52 [warn]  will retry in 400ms...                       module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:53 [warn]  attempt 5/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:53 [warn]  will retry in 800ms...                       module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:54 [warn]  attempt 6/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:54 [warn]  will retry in 1600ms...                      module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:55 [warn]  attempt 7/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:55 [warn]  will retry in 3200ms...                      module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:18:59 [warn]  attempt 8/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:19:05 [warn]  attempt 9/9: Unable to connect to the database: password authentication failed for user "nocobase" module=database method=auth app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:19:05 [error] Unable to connect to the database            stack=Error: Unable to connect to the database
    at _AsyncEmitter.auth (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\@nocobase\database\lib\database.js:657:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AsyncEmitter.authenticate (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\@nocobase\server\lib\application.js:419:5)
    at async Object.callback (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\@nocobase\server\lib\application.js:744:9)
    at async _AppCommand.parseAsync (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\@nocobase\server\node_modules\commander\lib\command.js:935:5)
    at async _AsyncEmitter.runAsCLI (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\@nocobase\server\lib\application.js:506:23) module=application app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465 dataSourceKey=main
2024-09-04 17:19:05 [error] password authentication failed for user "nocobase" stack=SequelizeConnectionError: password authentication failed for user "nocobase"
    at Client._connectionCallback (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\sequelize\src\dialects\postgres\connection-manager.js:196:24)
    at Client._handleErrorWhileConnecting (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\pg\lib\client.js:327:19)
    at Client._handleErrorMessage (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\pg\lib\client.js:347:19)
    at Connection.emit (node:events:519:28)
    at Connection.emit (node:domain:488:12)
    at C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\pg\lib\connection.js:117:12
    at Parser.parse (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\pg-protocol\src\parser.ts:104:9)
    at Socket.<anonymous> (C:\Users\SysAdmin\Desktop\my-nocobase-app\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12) app=main reqId=c88d7ed0-1098-4f16-b45d-dd4dce407465
Done in 22.95s.`

Env:
`APP_ENV=development
APP_KEY=xxxxxxx
APP_PORT=13000

API_BASE_PATH=/api/
API_BASE_URL=

PLUGIN_PACKAGE_PREFIX=

DB_LOGGING=off
DB_DIALECT=postgres
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=nocobase
DB_USER=nocobase
DB_PASSWORD=nocobase

INIT_ROOT_EMAIL=admin@nocobase.com
INIT_ROOT_PASSWORD=admin123
INIT_ROOT_NICKNAME=Super Admin
INIT_ROOT_USERNAME=nocobase
`

## * Environment
Windows 10 

- NocoBase version: latest

- Database type and version: PostgreSQL 16.x
  

- OS: windows 10 

- Deployment Methods: NA

- Docker image version: NA

- NodeJS version: 20.17.0

## Screenshots

![image](https://github.com/user-attachments/assets/55f428f4-2d2c-4659-82ee-64074c1d3a7c)

**Comment by pehua** [comment]
Hello. Consider reviewing the Postgres database user and pass and configuring the database owner as a nocobase user.

**Comment by MMirabito** [comment]
@pehua 
thanks I manually added the user it's connecting but there is no schema. I do  not understand what step I missed 

thanks
max

`
Installed node and yarn 
yarn create nocobase-app my-nocobase-app -d postgres \
   -e DB_HOST=localhost \
   -e DB_PORT=5432 \
   -e DB_DATABASE=nocobase \
   -e DB_USER=nocobase \
   -e DB_PASSWORD=nocobase \
   -e TZ=Asia/Shanghai

$ cd my-nocobase-app
$ yarn install
$ yarn nocobase install --lang=en-US
$ yarn dev
`

it's failing on '$ yarn nocobase install --lang=en-US'

`2024-09-04 20:55:15 [debug] create database instance: {"sync":{"alter":{"drop":false},"force":false},"logging":false,"dialect":"postgres","username":"nocobase","database":"nocobase","port":"5432","timezone":"-04:00","underscored":false,"migrator":{"context":{"app":{"appName":"main","name":"main"}}},"logger":{}} meta={"databaseInstanceId":"Xd3AMm6RAe6TPFox9Prw7"} module=database app=main reqId=54d7fa07-1cf0-4d62-8693-f402264bf547 dataSourceKey=main
2024-09-04 20:55:15 [info]  add app main into supervisor                 module=application submodule=supervisor method=addApp app=main reqId=54d7fa07-1cf0-4d62-8693-f402264bf547 dataSourceKey=main
2024-09-04 20:55:15 [warn]  attempt 1/9: Unable to connect to the database: database "nocobase" does not exist module=database method=auth app=main reqId=54d7fa07-1cf0-4d62-8693-f402264bf547 dataSourceKey=main
2024-09-04 20:55:15 [warn]  will retry in 50ms...                        module=database method=auth app=main reqId=54d7fa07-1cf0-4d62-8693-f402264bf547 dataSourceKey=main`

is one of the estep below supposed to create it

`$ cd my-nocobase-app
$ yarn install
$ yarn nocobase install
$ yarn dev
`
