### ISSUE TITLE
main分支启动报错

### ISSUE THREAD

**Issue by meimosor** [nocobase/nocobase#522]
## 问题描述

拉起最新main 分支启动 nocobase 报错，无法正常运行

Version
main 分支

How To Reproduce
执行如下命令：

git clone https://github.com/nocobase/nocobase.git
cd nocobase
cp .env.example .env 
yarn
yarn nocobase install --lang=zh-CN
yarn build
yarn start
## 运行环境

- node: v16.14.2
- yarn: 1.22.18
- Version 最新版

## 报错信息

`
$ nocobase start
Connection has been established successfully.
Start installing NocoBase
{
  err: Error
      at Query.run (D:\GiteeWork\nocobase\node_modules\sequelize\lib\dialects\mysql\query.js:46:25)
      at D:\GiteeWork\nocobase\node_modules\sequelize\lib\sequelize.js:626:28
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async MySQLQueryInterface.insert (D:\GiteeWork\nocobase\node_modules\sequelize\lib\dialects\abstract\query-interface.js:749:21)
      at async model.save (D:\GiteeWork\nocobase\node_modules\sequelize\lib\model.js:3987:35)
      at async Function.create (D:\GiteeWork\nocobase\node_modules\sequelize\lib\model.js:2216:12) {
    name: 'SequelizeUniqueConstraintError',
    errors: [ [ValidationErrorItem] ],
    fields: { name: 'local' },
    parent: Error: Duplicate entry 'local' for key 'name'
        at Packet.asError (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packets\packet.js:728:17)
        at Execute.execute (D:\GiteeWork\nocobase\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:456:32)
        at PacketParser.onPacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:85:12)
        at PacketParser.executeStart (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:92:25)
        at Socket.emit (node:events:526:28)
        at Socket.emit (node:domain:475:12)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9) {
      code: 'ER_DUP_ENTRY',
      errno: 1062,
      sqlState: '23000',
      sqlMessage: "Duplicate entry 'local' for key 'name'",
      sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);',
      parameters: [Array]
    },
    original: Error: Duplicate entry 'local' for key 'name'
        at Packet.asError (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packets\packet.js:728:17)
        at Execute.execute (D:\GiteeWork\nocobase\node_modules\mysql2\lib\commands\command.js:29:26)
        at Connection.handlePacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:456:32)
        at PacketParser.onPacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:85:12)
        at PacketParser.executeStart (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.<anonymous> (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:92:25)
        at Socket.emit (node:events:526:28)
        at Socket.emit (node:domain:475:12)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9) {
      code: 'ER_DUP_ENTRY',
      errno: 1062,
      sqlState: '23000',
      sqlMessage: "Duplicate entry 'local' for key 'name'",
      sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);',
      parameters: [Array]
    },
    sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);'
  }
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (D:\GiteeWork\nocobase\node_modules\sequelize\lib\dialects\mysql\query.js:46:25)
    at D:\GiteeWork\nocobase\node_modules\sequelize\lib\sequelize.js:626:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (D:\GiteeWork\nocobase\node_modules\sequelize\lib\dialects\abstract\query-interface.js:749:21)
    at async model.save (D:\GiteeWork\nocobase\node_modules\sequelize\lib\model.js:3987:35)
    at async Function.create (D:\GiteeWork\nocobase\node_modules\sequelize\lib\model.js:2216:12) {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'name must be unique',
      type: 'unique violation',
      path: 'name',
      value: 'local',
      origin: 'DB',
      instance: storages {
        dataValues: {
          rules: {},
          path: '',
          id: null,
          title: '本地存储',
          type: 'local',
          name: 'local',
          baseUrl: 'http://localhost:13000/storage/uploads',
          options: { documentRoot: 'storage/uploads' },
          default: true,
          updatedAt: 2022-06-21T16:07:02.537Z,
          createdAt: 2022-06-21T16:07:02.537Z
        },
        _previousDataValues: {
          title: undefined,
          type: undefined,
          name: undefined,
          baseUrl: undefined,
          options: undefined,
          default: undefined
        },
        _changed: Set(6) {
          'title',
          'type',
          'name',
          'baseUrl',
          'options',
          'default'
        },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  fields: { name: 'local' },
  parent: Error: Duplicate entry 'local' for key 'name'
      at Packet.asError (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (D:\GiteeWork\nocobase\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry 'local' for key 'name'",
    sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);',
    parameters: [
      '2022-06-21 16:07:02',
      '2022-06-21 16:07:02',
      '本地存储',
      'local',
      'local',
      '{"documentRoot":"storage/uploads"}',
      '{}',
      '',
      'http://localhost:13000/storage/uploads',
      true
    ]
  },
  original: Error: Duplicate entry 'local' for key 'name'
      at Packet.asError (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (D:\GiteeWork\nocobase\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (D:\GiteeWork\nocobase\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\GiteeWork\nocobase\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry 'local' for key 'name'",
    sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);',
    parameters: [
      '2022-06-21 16:07:02',
      '2022-06-21 16:07:02',
      '本地存储',
      'local',
      'local',
      '{"documentRoot":"storage/uploads"}',
      '{}',
      '',
      'http://localhost:13000/storage/uploads',
      true
    ]
  },
  sql: 'INSERT INTO `storages` (`id`,`createdAt`,`updatedAt`,`title`,`name`,`type`,`options`,`rules`,`path`,`baseUrl`,`default`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?,?);'
}
D:\GiteeWork\nocobase\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js install --silent
    at makeError (D:\GiteeWork\nocobase\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\GiteeWork\nocobase\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (D:\GiteeWork\nocobase\packages\core\cli\src\commands\start.js:42:7) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js install --silent',
  command: 'node ./packages/app/server/lib/index.js install --silent',
  escapedCommand: 'node "./packages/app/server/lib/index.js" install --silent',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by meimosor** [comment]
数据库环境已在env里面改成mysql,数据库表都初始化了，但是启动报错，yarn dev也是报这个错

**Comment by chenos** [comment]
@meimosor mysql 是什么版本？是 8.0 吗？

**Comment by meimosor** [comment]
> @meimosor mysql 是什么版本？是 8.0 吗？
是的，Mysql 8.0.17

**Comment by meimosor** [comment]
.env的配置：
`
################# DATABASE #################

DB_DIALECT=mysql
# DB_STORAGE=storage/db/nocobase.sqlite
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nocobase
DB_USER=root
DB_PASSWORD=123456
# DB_LOGGING=on
#DB_TABLE_PREFIX=nocobase_
`

**Comment by chenos** [comment]
看错误信息 `yarn start` 是生产环境命令，还不支持在 win 平台上运行，win 本地用 `yarn dev`

**Comment by meimosor** [comment]
> 看错误信息 `yarn start` 是生产环境命令，还不支持在 win 平台上运行，win 本地用 `yarn dev`

yarn dev也尝试了，运行不起来，报错信息一样

**Comment by meimosor** [comment]
windows上运行是有问题。同样操作在ubuntu上可以正常编译和访问

**Comment by shendengnian** [comment]
解决了吗？我也遇到了这个问题，window系统先yarn dev有时会报这个错，打开了本机vpn代理后重启几次又好了，在centos下直接就是运行不起来，就是楼上的那个报错

**Comment by meimosor** [comment]
> 解决了吗？我也遇到了这个问题，window系统先yarn dev有时会报这个错，打开了本机vpn代理后重启几次又好了，在centos下直接就是运行不起来，就是楼上的那个报错



没有解决，最后用的ubuntu解决的

**Comment by shendengnian** [comment]
> > 解决了吗？我也遇到了问题，window系统Senyarn dev有时会直接报错，打开本vpn代理后重启了这个机器好几次了，在centos下就是运行不起来，就是又楼上的那个报错
> 
> 没有解决，最后用的 ubuntu 解决的

我的今天解决了。。给你的建议就是把yarn启动的超时时间设置高一点，多试几次。。。就搞定了

**Comment by shendengnian** [comment]
> > 解决了吗？我也遇到了问题，window系统Senyarn dev有时会直接报错，打开本vpn代理后重启了这个机器好几次了，在centos下运行就是不起来，就是错楼上的那个报
> 
> 没有解决，最后用的 ubuntu 解决的

我的解决了。给你的建议就是把yarn启动的超时时间设置高一点，多试几次。。。就搞定了
