### ISSUE TITLE
The interface is throwing an error when i start the project

### ISSUE THREAD

**Issue by liujunning** [nocobase/nocobase#5266]
## * Describe the bug

After downloading the source code via Git and following the steps in the official documentation, when running the yarn dev command, a 504 error occurs at 192.168.1.17:13000/api/app:getLang?locale.

## * Environment
 
MySQL 8.4.2
 
- Database type and version: 
Macos：13.6.9 (22G830)
- OS:
 
- Deployment Methods:
 
- Docker image version:
 
- NodeJS version:
node:v18.19.0

## Logs
 yarn run dev
 
 2024-09-13 11:41:44 [info]  add app main into supervisor                 module=application submodule=supervisor method=addApp app=main reqId=ae3712f7-8a2d-4b3d-91f0-40b5cf452415 dataSourceKey=main
node:assert:172
  throw err;
  ^

AssertionError [ERR_ASSERTION]: unknown message code: 4a
    at Parser.handlePacket (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/parser.ts:202:16)
    at Parser.parse (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}

Node.js v18.19.0

**Comment by chareice** [comment]
The error message indicates a problem occurred while establishing a database connection. Please check your database connection configuration.
