### ISSUE TITLE
 plugin-mobile 插件在mysql 8.0.30 启用失败

### ISSUE THREAD

**Issue by mycheng** [nocobase/nocobase#5328]
plugin-mobile 插件在mysql 8.0.30 启用失败
报错如下

2024-09-26 15:34:22 [error] Failed to enable plugin                      stack=Error: Failed to enable plugin
    at _AppCommand.<anonymous> (D:\github\my-nocobase\node_modules\@nocobase\server\lib\commands\pm.js:72:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AppCommand.parseAsync (D:\github\my-nocobase\node_modules\@nocobase\server\node_modules\commander\lib\command.js:935:5)
    at async _AsyncEmitter.runAsCLI (D:\github\my-nocobase\node_modules\@nocobase\server\lib\application.js:506:23) module=application app=main reqId=5c66948e-fae6-4ff9-9020-32814711bd14 dataSourceKey=main
2024-09-26 15:34:22 [error] This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.' stack=Error
    at Query.run (D:\github\my-nocobase\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at D:\github\my-nocobase\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _SyncRunner.handlePrimaryKeyBeforeSync (D:\github\my-nocobase\node_modules\@nocobase\database\lib\sync-runner.js:120:9)
    at async _SyncRunner.runSync (D:\github\my-nocobase\node_modules\@nocobase\database\lib\sync-runner.js:87:7)
    at async main_mobileRoutes_path.sync (D:\github\my-nocobase\node_modules\@nocobase\database\lib\model.js:57:12)
    at async _Collection.sync (D:\github\my-nocobase\node_modules\@nocobase\database\lib\collection.js:559:7)
    at async _AsyncEmitter.<anonymous> (D:\github\my-nocobase\node_modules\@nocobase\plugin-collection-tree\dist\server\plugin.js:73:13)
    at async _AsyncEmitter.emitAsync (D:\github\my-nocobase\node_modules\@nocobase\utils\lib\mixin\AsyncEmitter.js:66:7)
    at async mobileRoutes.<anonymous> (D:\github\my-nocobase\node_modules\@nocobase\database\lib\model-hook.js:88:9) app=main reqId=5c66948e-fae6-4ff9-9020-32814711bd14

**Comment by zhouyanliang** [comment]
https://forum.nocobase.com/  请在中文社区发布中文内容
