### ISSUE TITLE
Start with Docker install, 502 error 

### ISSUE THREAD

**Issue by Rayi** [nocobase/nocobase#5669]
## * Describe the bug

Follow the install intro https://docs-cn.nocobase.com/welcome/getting-started/installation/docker-compose
and start the docker server.

![image](https://github.com/user-attachments/assets/ddfedf6b-6d28-4d14-89d2-91b2891b0583)

`/api/app:getLang?locale` throw 502 error.

## * Environment
  

- OS: MacOS 

- Deployment Methods: Docker

- Docker image version:
- 
![image](https://github.com/user-attachments/assets/35f81eb3-27b6-492b-b6e7-6a418dfbd03a)

**Comment by Rayi** [comment]
```
2024-11-18 12:05:31 2024-11-18T12:05:31: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2024-11-18 12:05:31 2024-11-18T12:05:31: PM2 log: App [index:0] starting in -fork mode-
2024-11-18 12:05:31 2024-11-18T12:05:31: PM2 log: App [index:0] online
2024-11-18 12:05:32 Error: listen ENOTSUP: operation not supported on socket /app/nocobase/storage/gateway.sock
2024-11-18 12:05:32     at Server.setupListenHandle [as _listen2] (node:net:1800:21)
2024-11-18 12:05:32     at listenInCluster (node:net:1865:12)
2024-11-18 12:05:32     at Server.listen (node:net:1964:5)
2024-11-18 12:05:32     at IPCSocketServer.buildServer (/app/nocobase/node_modules/@nocobase/server/lib/gateway/ipc-socket-server.js:95:18)
2024-11-18 12:05:32     at _Gateway.startIPCSocketServer (/app/nocobase/node_modules/@nocobase/server/lib/gateway/index.js:335:69)
2024-11-18 12:05:32     at _Gateway.start (/app/nocobase/node_modules/@nocobase/server/lib/gateway/index.js:332:10)
2024-11-18 12:05:32     at _Gateway.run (/app/nocobase/node_modules/@nocobase/server/lib/gateway/index.js:283:12)
2024-11-18 12:05:32     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-11-18 12:05:32   code: 'ENOTSUP',
2024-11-18 12:05:32   errno: -95,
2024-11-18 12:05:32   syscall: 'listen',
2024-11-18 12:05:32   address: '/app/nocobase/storage/gateway.sock',
2024-11-18 12:05:32   port: -1
2024-11-18 12:05:32 }
```

container log with error content .

**Comment by hongboji** [comment]
Please wait for a few seconds and then refresh your browser to check if you have accessed it properly.

**Comment by shijian-git** [comment]
It should be that the application is closed abnormally, causing storage/gateway.sock to remain in the storage directory, which can be solved by restarting the application after deleting the file.

**Comment by guangyuli124** [comment]
Thank you Shijian, I solved this issue with your approach.
