### ISSUE TITLE
tree collection

### ISSUE THREAD

**Issue by GloryET-zh** [nocobase/nocobase#5677]
# 1During the testing of the tree structure table page component (table), after clicking on the parent record to pop up a dialog box, configuring the current record, and selecting "Sub-table" for the unique attribute field component of the {parent record}, an error occurred when updating the data as follows:
在树结构表的页面组件（表格）测试时，通过点击父记录弹出的弹窗，配置了当前记录后，对{父记录}的特有属性 字段组件 选择了：子表格 后 更新数据，报错如下,
```
TypeError: (le.value || []).map is not a function
at Ln (http://127.0.0.1:8088/p__index.4ee20a1f.async.js:924:1497)
at pc.displayName (http://127.0.0.1:8088/p__index.4ee20a1f.async.js:924:2833)
at http://127.0.0.1:8088/npm._at_formily.3ea3d9f9.async.js:100:311372
at I.track (http://127.0.0.1:8088/npm._at_formily.3ea3d9f9.async.js:100:329349)
at dr (http://127.0.0.1:8088/npm._at_formily.3ea3d9f9.async.js:100:310953)
at K (http://127.0.0.1:8088/npm._at_formily.3ea3d9f9.async.js:100:311351)
at dn (http://127.0.0.1:8088/umi.44718844.js:13:20336)
at dl (http://127.0.0.1:8088/umi.44718844.js:15:3152)
at tc (http://127.0.0.1:8088/umi.44718844.js:15:2364)
at ec (http://127.0.0.1:8088/umi.44718844.js:15:1906)
at Nc (http://127.0.0.1:8088/umi.44718844.js:15:47837)
at Cc (http://127.0.0.1:8088/umi.44718844.js:15:40194)
at rf (http://127.0.0.1:8088/umi.44718844.js:15:40122)
at ks (http://127.0.0.1:8088/umi.44718844.js:15:39976)
at Cl (http://127.0.0.1:8088/umi.44718844.js:15:36279)
at Tc (http://127.0.0.1:8088/umi.44718844.js:15:37085)
at So (http://127.0.0.1:8088/umi.44718844.js:13:3282)
at http://127.0.0.1:8088/umi.44718844.js:15:34612
```
# 2 
[logs.tar.gz](https://github.com/user-attachments/files/17800278/logs.tar.gz)
Moreover, the copy function on the bug report submission page does not work as expected; the output in the clipboard is [object Object]
而且bug信息提交页的复制功能不生效复制的，粘贴板的输出是[object Object]

**Comment by hongboji** [comment]
Is it possible to request a demo on the official website and do a reproduction that gives the problem url?
The application address is as follows:https://demo.nocobase.com/new
