### ISSUE TITLE
yarn start 启动不成功 报错

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#568]
换了好几个环境，都是这样，不知道为何？
d:\>yarn  start
yarn run v1.22.19
$ nocobase start
node:internal/validators:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:429:7)
    at Object.instanciate (  d:\my-nocobase-app\node_modules\pm2\lib\binaries\Runtime4Docker.js:66:47)
    at Command.<anonymous> (D:\my-nocobase-app\node_modules\pm2\lib\binaries\Runtime4Docker.js:54:13)
    at Command.listener (D:\my-nocobase-app\node_modules\pm2\node_modules\commander\index.js:315:8)
    at Command.emit (node:events:527:28)
    at Command.parseArgs (D:\my-nocobase-app\node_modules\pm2\node_modules\commander\index.js:651:12)
    at Command.parse (D:\my-nocobase-app\node_modules\pm2\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\my-nocobase-app\node_modules\pm2\lib\binaries\Runtime4Docker.js:190:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Done in 1.90s.

**Comment by chenos** [comment]
yarn start 是生产环境命令，现在不支持在 Windows 下运行。本地用 yarn dev

**Comment by aiwenForGit** [comment]
感谢回复！后续可以支持么？

**Comment by chenos** [comment]
> 感谢回复！后续可以支持么？

已支持 https://github.com/nocobase/nocobase/commit/c64e32945e440ba856c4dbef396d805a5321ea0c
