### ISSUE TITLE
git 升级报错

### ISSUE THREAD

**Issue by nakas888** [nocobase/nocobase#689]
λ yarn dev
yarn run v1.21.1
$ nocobase dev
WAIT: TypeScript compiling...
E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/core/database/src/database.ts:456:30 - error TS2345: Argument of type 'string | number | symbol' is not assignable to parameter of type 'keyof SequelizeHooks<M, TModelAttributes, TCreationAttributes>'.
  Type 'string' is not assignable to type 'keyof SequelizeHooks<M, TModelAttributes, TCreationAttributes>'.

456       this.sequelize.addHook(type, this.modelHook.buildSequelizeHook(type));
                                 ~~~~

    at createTSError (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\@commitlint\load\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2345 ]
}
E:\nocobase\gitnocobase\my-nocobase-app\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: ts-node -P ./tsconfig.server.json -r tsconfig-paths/register ./packages/app/server/src/index.ts install --silent
    at makeError (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\execa\lib\error.js:60:11)
    at handlePromise (E:\nocobase\gitnocobase\my-nocobase-app\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.runAppCommand (E:\nocobase\gitnocobase\my-nocobase-app\packages\core\cli\src\util.js:122:5)
    at async Command.<anonymous> (E:\nocobase\gitnocobase\my-nocobase-app\packages\core\cli\src\commands\dev.js:48:7) {
  shortMessage: 'Command failed with exit code 1: ts-node -P ./tsconfig.server.json -r tsconfig-paths/register ./packages/app/server/src/index.ts install --silent',
  command: 'ts-node -P ./tsconfig.server.json -r tsconfig-paths/register ./packages/app/server/src/index.ts install --silent',
  escapedCommand: 'ts-node -P "./tsconfig.server.json" -r "tsconfig-paths/register" "./packages/app/server/src/index.ts" install --silent',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

E:\nocobase\gitnocobase\my-nocobase-app (main -> origin)

**Comment by chenos** [comment]
推荐使用 LTS 版本 v16 再试试

**Comment by nakas888** [comment]
装了nodejs16.16 还是不行，只能重装。
