### ISSUE TITLE
Cannot find module '@nocobase/database' or its corresponding type declarations

### ISSUE THREAD

**Issue by BinZhiZhu** [nocobase/nocobase#69]
deploy流程上是不是应该在README中体现更具体一些，我描述下我刚刚的流程：

1. git clone
2. npm i
3. npm run bootstrap 其实也就是lerna bootstrap,安装各模块的依赖
4. npm run start 

```
➜  nocobase git:(master) ✗ npm run start    

> root@ start /Users/apple/docker/wwwroot/nocobase
> cd packages/app && npm start


> @nocobase/app@0.4.0-alpha.0 start /Users/apple/docker/wwwroot/nocobase/packages/app
> concurrently "nodemon" "umi dev"

[0] [nodemon] 2.0.7
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): ../**/*
[0] [nodemon] watching extensions: ts
[0] [nodemon] starting `ts-node ../api/src/index.ts`
[1] Starting the development server...
[1] ℹ Compiling Webpack
[0] 
[0] /Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:434
[0]     return new TSError(diagnosticText, diagnosticCodes)
[0]            ^
[0] TSError: ⨯ Unable to compile TypeScript:
[0] ../api/src/app.ts(6,33): error TS2307: Cannot find module '@nocobase/database' or its corresponding type declarations.
[0] 
[0]     at createTSError (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:434:12)
[0]     at reportTSError (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:438:19)
[0]     at getOutput (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:578:36)
[0]     at Object.compile (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:775:32)
[0]     at Module.m._compile (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:858:43)
[0]     at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
[0]     at Object.require.extensions.<computed> [as .ts] (/Users/apple/docker/wwwroot/nocobase/node_modules/ts-node/src/index.ts:861:12)
[0]     at Module.load (internal/modules/cjs/loader.js:798:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
[0]     at Module.require (internal/modules/cjs/loader.js:838:19)
[0] [nodemon] app crashed - waiting for file changes before starting...
^C[0] nodemon exited with code 130
[1] umi dev exited with code 0

```

**Comment by BinZhiZhu** [comment]
@nocobase/database 这个包我搜代码，大致是plugin这些模块的依赖，但是我lerna bootstrap已经安装成功了呀？难道我要clean一下，重新lerna bootstrap？我是伪前端，觉得项目挺有趣，所以打算跑起来看看，如果是很明显我看漏了什么，望告知哈~

**Comment by chenos** [comment]
要配置好环境变量，在 ` .env` 文件里，主要是数据库信息，要用 postgresql 数据库

```bash
npm install
npm run bootstrap
npm build  # 这一步不要忘了
npm run start
```

**Comment by BinZhiZhu** [comment]
> 要配置好环境变量，在 ` .env` 文件里，主要是数据库信息，要用 postgresql 数据库
> 
> ```shell
> npm install
> npm run bootstrap
> npm build  # 这一步不要忘了
> npm run start
> ```

OK吧，我是直接看README跑的，.env没留意，只支持postgresql的db类型的话最好在文档补充一下，因为有可能还有一些跟我这样的小白~~ 那谢谢了，我有空的时候再run起来看看

**Comment by chenos** [comment]
@BinZhiZhu 这几天会发布个 docker 镜像，用 docker 安装会方便一些。数据库理论上支持 postgresql、mysql、sqlite 等关系型数据库的。不过，现在在有些小细节上 mysql 和 sqlite 还不支持，接下来都会逐步完善

**Comment by BinZhiZhu** [comment]
> @BinZhiZhu 这几天会发布个 docker 镜像，用 docker 安装会方便一些。数据库理论上支持 postgresql、mysql、sqlite 等关系型数据库的。不过，现在在有些小细节上 mysql 和 sqlite 还不支持，接下来都会逐步完善

Nice 我本地也是docker-composer 环境 数据库最基本应先支持MySQL吧 相对来说使用率高 不过没看你的db是什么管理的 等好消息咯
