### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#698]
v0.7.4-alpha.1

编译报错
```TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/data/bigdata/nocobase/nocobase/packages/core/build/node_modules/gulp-typescript/release/output.js:130:43)
    at /data/bigdata/nocobase/nocobase/packages/core/build/node_modules/gulp-typescript/release/output.js:65:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (/data/bigdata/nocobase/nocobase/node_modules/duplexify/index.js:191:15)
    at /data/bigdata/nocobase/nocobase/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
/data/bigdata/nocobase/nocobase/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: nocobase-build
    at makeError (/data/bigdata/nocobase/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/data/bigdata/nocobase/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/data/bigdata/nocobase/nocobase/packages/core/cli/src/commands/build.js:28:9) {
  shortMessage: 'Command failed with exit code 1: nocobase-build',
  command: 'nocobase-build',
  escapedCommand: 'nocobase-build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chenos** [comment]
操作系统以及 nodejs 是什么版本的？

**Comment by chenos** [comment]
刚测试发现 v18 的确有点问题，推荐使用 LTS 版本 v16

**Comment by 625412505** [comment]
> 操作系统以及 nodejs 是什么版本的？
v16.14.2
![image](https://user-images.githubusercontent.com/82276246/181866653-6246c3cc-20a0-4297-a3d5-101079de914d.png)

**Comment by 625412505** [comment]
删除node_modules，重新yarn install & yarn build，可以编译成功。
