### ISSUE TITLE
yarn nocobase install error

### ISSUE THREAD

**Issue by elicip** [nocobase/nocobase#742]
## Describe the bug

Run `yarn nocobase install`, and shows
```
WAIT: TypeScript compiling...
Executing (default): SELECT 1+1 AS result
Connection has been established successfully.
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'nocobase';
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'nocobase';
Start installing NocoBase
Executing (default): select version() as version
The database only supports MySQL 8.0.17 and above, SQLite 3.x and PostgreSQL 10+
Executing (default): SELECT `id`, `createdAt`, `updatedAt`, `key`, `title`, `enabled`, `description`, `type`, `config`, `useTransaction`, `executed`, `allExecuted`, `current` FROM `workflows` AS `workflows` WHERE `workflows`.`enabled` = true;
/home/elicip/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:46
    const errForStack = new Error();
                        ^
Error
    at Query.run (/home/elicip/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:46:25)
    at /home/elicip/nocobase/node_modules/sequelize/lib/sequelize.js:626:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.select (/home/elicip/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
    at async Function.findAll (/home/elicip/nocobase/node_modules/sequelize/lib/model.js:1754:21) {
  name: 'SequelizeDatabaseError',
  parent: Error: Table 'nocobase.workflows' doesn't exist
      at Packet.asError (/home/elicip/nocobase/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/home/elicip/nocobase/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/home/elicip/nocobase/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'nocobase.workflows' doesn't exist",
    sql: 'SELECT `id`, `createdAt`, `updatedAt`, `key`, `title`, `enabled`, `description`, `type`, `config`, `useTransaction`, `executed`, `allExecuted`, `current` FROM `workflows` AS `workflows` WHERE `workflows`.`enabled` = true;',
    parameters: undefined
  },
  original: Error: Table 'nocobase.workflows' doesn't exist
      at Packet.asError (/home/elicip/nocobase/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/home/elicip/nocobase/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/home/elicip/nocobase/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/home/elicip/nocobase/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'nocobase.workflows' doesn't exist",
    sql: 'SELECT `id`, `createdAt`, `updatedAt`, `key`, `title`, `enabled`, `description`, `type`, `config`, `useTransaction`, `executed`, `allExecuted`, `current` FROM `workflows` AS `workflows` WHERE `workflows`.`enabled` = true;',
    parameters: undefined
  },
  sql: 'SELECT `id`, `createdAt`, `updatedAt`, `key`, `title`, `enabled`, `description`, `type`, `config`, `useTransaction`, `executed`, `allExecuted`, `current` FROM `workflows` AS `workflows` WHERE `workflows`.`enabled` = true;',
  parameters: undefined
}
```

## Version

v0.7.4-alpha.7

## How To Reproduce

mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by chenos** [comment]
麻烦贴一下 sql 查询 `select version()` 输出的是什么？

**Comment by elicip** [comment]
@chenos 

```
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 8.0.30-0ubuntu0.20.04.2 |
+-------------------------+
1 row in set (0.00 sec)
```
