### ISSUE TITLE
使用MySql数据库的时候出错 npm run db-migrate init 出错

### ISSUE THREAD

**Issue by Red5Timor** [nocobase/nocobase#76]
错误内容
process.env.NOCOBASE_ENV 
{
  database: {
    username: 'root',
    password: 'root',
    database: 'nocobase',
    host: 'localhost',
    port: '3306',
    dialect: 'mysql',
    dialectOptions: { charset: 'utf8mb4', collate: 'utf8mb4_unicode_ci' },
    pool: { max: 5, min: 0, acquire: 30000, idle: 10000 },
    logging: false,
    define: {},
    sync: { force: true, alter: [Object] }
  },
  resourcer: { prefix: '/api' }
}
Ignoring invalid configuration option passed to Connection: collate. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: collate. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
(node:9767) UnhandledPromiseRejectionWarning: Error: Invalid value {}
    at Object.escape (/var/www/nocobasedemo/node_modules/sequelize/lib/sql-string.js:65:11)
    at MySQLQueryGenerator.escape (/var/www/nocobasedemo/node_modules/sequelize/lib/dialects/abstract/query-generator.js:994:22)
    at MySQLQueryGenerator.attributeToSQL (/var/www/nocobasedemo/node_modules/sequelize/lib/dialects/mysql/query-generator.js:379:36)
    at MySQLQueryGenerator.attributesToSQL (/var/www/nocobasedemo/node_modules/sequelize/lib/dialects/mysql/query-generator.js:434:45)
    at MySQLQueryInterface.createTable (/var/www/nocobasedemo/node_modules/sequelize/lib/dialects/abstract/query-interface.js:222:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.sync (/var/www/nocobasedemo/node_modules/sequelize/lib/model.js:1300:5)
    at async Sequelize.sync (/var/www/nocobasedemo/node_modules/sequelize/lib/sequelize.js:793:35)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9767) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9767) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

npm run bootstrap 在这一步的时候要提高到root操作。
请问目前数据库是否只支持PostgreSQL ，
以及在windows环境下测试,文件中包含":"的文件不能使用，需要修改文件名称

**Comment by Red5Timor** [comment]
再换成PostgreSQL 后没有这个问题了。

**Comment by chenos** [comment]
访问报的什么错误？方便贴一下吗，如果是 docker 环境，要访问映射的端口

**Comment by Red5Timor** [comment]
是在windows 上运行出现的错误（不记得具体是什么问题了），后面改成centos后好了。
在系统使用过程中，我在对表的操作时出现一张表和另一张表内混淆的情况（表的内容一致），删除后出现，一张表种包含所有字段
，在删除这表种数据后出现系统崩溃的情况（就是所有页面报错，主页已经进不去了），重新初始化数据库后才能使用。

**Comment by Red5Timor** [comment]
在选择关联表->表界面，点击所属数据表（表A），在显示的所有的表（表A,表B...），字段都是表A的字段,所有的增删字段都对表A进行操作。

**Comment by Red5Timor** [comment]
请问个问题，在哪实现的插入一条数据（插入新建表的数据）后，在数据库新建一张表

**Comment by chenos** [comment]
在 plugin-collections 插件里

**Comment by Red5Timor** [comment]
(node:16408) UnhandledPromiseRejectionWarning: SequelizeConnectionError: �û� "nocobase" Password ��֤ʧ��
    at Client._connectionCallback (D:\PersonData\GitData\nocobase\packages\database\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:184:24)
    at Client._handleErrorWhileConnecting (D:\PersonData\GitData\nocobase\node_modules\pg\lib\client.js:305:19)
    at Client._handleErrorMessage (D:\PersonData\GitData\nocobase\node_modules\pg\lib\client.js:325:19)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:483:12)
    at D:\PersonData\GitData\nocobase\node_modules\pg\lib\connection.js:114:12
    at Parser.parse (D:\PersonData\GitData\nocobase\node_modules\pg-protocol\src\parser.ts:104:9)
    at Socket.<anonymous> (D:\PersonData\GitData\nocobase\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
(node:16408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(
). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

//在WINDOW下系统报错，启动不了server端

**Comment by Red5Timor** [comment]
以及能给个联系方式吗，我们在测试使用这个系统

**Comment by zhouyanliang** [comment]
> 以及能给个联系方式吗，我们在测试使用这个系统
> 有些问题希望能请教一下。

Hi 是否方便介绍一下你那边的使用场景？ 为确保效率可以先通过邮件联系：hello@nocobase.com

**Comment by imaegoo** [comment]
遇到相同的错误，操作系统：Windows 10，数据库：MySQL 5.7.21

```
yarn run v1.22.10
$ ts-node -r dotenv/config ./packages/api/src/migrate.ts init
process.env.NOCOBASE_ENV 
{
  database: {
    username: 'root',
    password: 'password',
    database: 'nocobase',
    host: 'localhost',
    port: '3306',
    dialect: 'mysql',
    dialectOptions: { charset: 'utf8mb4', collate: 'utf8mb4_unicode_ci' },
    pool: { max: 5, min: 0, acquire: 30000, idle: 10000 },
    logging: false,
    define: {},
    sync: { force: true, alter: [Object] }
  },
  resourcer: { prefix: '/api' }
}
Ignoring invalid configuration option passed to Connection: collate. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: collate. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
(node:17096) UnhandledPromiseRejectionWarning: Error: Invalid value {}
    at Object.escape (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\sql-string.js:65:11)
    at MySQLQueryGenerator.escape (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\dialects\abstract\query-generator.js:994:22)
    at MySQLQueryGenerator.attributeToSQL (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\dialects\mysql\query-generator.js:379:36)
    at MySQLQueryGenerator.attributesToSQL (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\dialects\mysql\query-generator.js:434:45)
    at MySQLQueryInterface.createTable (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\dialects\abstract\query-interface.js:222:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.sync (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\model.js:1300:5)
    at Sequelize.sync (E:\iMaeGoo\Documents\workspace\nocobase\packages\database\node_modules\sequelize\lib\sequelize.js:793:35)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 57.00s.
```

**Comment by dfar2008** [comment]
win10+postgres13 开始安装遇到冒号(:)文件路径问题，后来把server.js中的有关路径的":"改成"_"，node_modules\@nocobase\plugin-pages\lib\actions 中的路径也改了，npx nocobase db-init这一步运行成功了，运行npx nocobase start系统报错，报如下错误：
http://localhost:23000/
Executing (default): SELECT "id", "title", "name", "type", "options", "rules", "path", "base_url" AS "baseUrl", "default", "created_at", "updated_at" FROM "storages" AS "storages" WHERE "storages"."type" = 'local';

  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:124:11)
      at Object.join (path.js:375:7)
      at getDocumentRoot (E:\svn\my-nocobase-project\node_modules\@nocobase\plugin-file-manager\lib\storages\local.js:86:105)
      at E:\svn\my-nocobase-project\node_modules\@nocobase\plugin-file-manager\lib\storages\local.js:135:72
      at Generator.next (<anonymous>)
      at fulfilled (E:\svn\my-nocobase-project\node_modules\@nocobase\plugin-file-manager\lib\storages\local.js:31:24)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
和楼上的错误信息一样，请问 @chenos 这个问题如何解决呢？谢谢。
