### ISSUE TITLE
源代码在 v0.7.4-alpha.7 下执行 yarn nocobase install

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#769]
## Describe the bug

clone 源代码在 `v0.7.4-alpha.7` 下执行 `yarn nocobase install --lang=zh-CN` 报错

报错堆栈：

```
/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/core/database/src/database.ts:462:30 - error TS2345: Argument of type 'string | number | symbol' is not assignable to parameter of type 'keyof SequelizeHooks<M, TModelAttributes, TCreationAttributes>'.
  Type 'string' is not assignable to type 'keyof SequelizeHooks<M, TModelAttributes, TCreationAttributes>'.

462       this.sequelize.addHook(type, this.modelHook.buildSequelizeHook(type));
                                 ~~~~

    at createTSError (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2345 ]
```

## Version

NocoBase version `v0.7.4-alpha.7`

node.js `v16.14.0`

## How To Reproduce

```bash
git clone https://github.com/nocobase/nocobase.git nocobase-tmp
cd nocobase-tmp

git checkout -b v0.7.4-alpha.7 v0.7.4-alpha.7

# 如果使用项目自带的 ./yarn.lock 则不会报错
rm yarn.lock

yarn nocobase install --lang=zh-CN

# 报错出现上述错误
/tmp/nocobase-tmp/node_modules/@commitlint/load/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
...

```

## Expected behavior

希望能在删除 `./yarn.lock` 后可以正常执行 build 相关命令。

因为需要使用私有registry (Verdaccio)

## Desktop (please complete the following information)

- OS: macOS 12.4 (21F79)
- node.js  v16.14.0

**Comment by chenos** [comment]
yarn.lock 不能删的，也不影响 Verdaccio 吧？

**Comment by MarshalW** [comment]
>也不影响` Verdaccio 吧？

还是有区别的，比如用 `Verdaccio` 的话，`yarn.lock` 类似这样：

```
"@ampproject/remapping@^2.1.0":
  version "2.2.0"
  resolved "http://192.168.0.120:4873/@ampproject%2fremapping/-/remapping-2.2.0.tgz#56c133824780de3174aed5ab6834f3026790154d"
  integrity sha512-qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==
  dependencies:
    "@jridgewell/gen-mapping" "^0.1.0"
    "@jridgewell/trace-mapping" "^0.3.9"
```

在 nocobase 的 `yarn.lock`:

```
"@ampproject/remapping@^2.1.0":
  version "2.2.0"
  resolved "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.0.tgz#56c133824780de3174aed5ab6834f3026790154d"
  integrity sha512-qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==
  dependencies:
    "@jridgewell/gen-mapping" "^0.1.0"
    "@jridgewell/trace-mapping" "^0.3.9"
``` 

不过我想了一下，因为 yarn.lock 文件统一使用依赖库的版本，所以确实不能随便更新。

因此我关闭这个问题。

我考虑的变通办法是，全替代 `yarn.lock` 的 registry 的 链接，估计这样可以解决问题。

**Comment by MarshalW** [comment]
全替代的方式是可以解决问题的。

即：将 yarn.lock 的 `registry.npmjs.org` 或者 `registry.yarnpkg.com` 全替代为本地 `Verdaccio` registry 的链接。

`.change-registry.sh`:

```bash
#!/bin/bash

sed_command="sed"

if [[ $OSTYPE == 'darwin'* ]]; then
  sed_command="gsed"
fi

registry="http://192.168.0.120:4873"

gsed -i -e "s#https://registry.npmjs.org#$registry#g" yarn.lock
```
