### ISSUE TITLE
npm run build failed 

### ISSUE THREAD

**Issue by zhuyifang** [nocobase/nocobase#78]
$ father-build
[
  'database',
  'resourcer',
  'actions',
  'client',
  'server',
  'api',
  'create-nocobase-app',
  'plugin-action-logs',
  'plugin-automations',
  'plugin-china-region',
  'plugin-collections',
  'plugin-export',
  'plugin-file-manager',
  'plugin-full-collections',
  'plugin-pages',
  'plugin-permissions',
  'plugin-users'
]
@nocobase/database: Clean dist directory
@nocobase/database: Build cjs with babel
@nocobase/database: Clean lib directory
@nocobase/database: Transform to cjs for src/__tests__/tables/tests.js
@nocobase/database: Transform to cjs for src/__tests__/utils/modules/fn.js
@nocobase/database: Transform to cjs for src/__tests__/utils/modules/obj.js
/Users/mo-fang/nocobase/node_modules/@types/express-serve-static-core/index.d.ts(589,18):error TS2430: Interface 'Response<ResBody, Locals, StatusCode>' incorrectly extends interface 'ServerResponse'.
  Property 'req' is optional in type 'Response<ResBody, Locals, StatusCode>' but required in type 'ServerResponse'.
/Users/mo-fang/nocobase/node_modules/@types/express/index.d.ts(58,55): error TS2344: Type 'Response<any, Record<string, any>>' does not satisfy the constraint 'ServerResponse'.
  Property 'req' is optional in type 'Response<any, Record<string, any>>' but required in type 'ServerResponse'.
@nocobase/database: Transform to cjs for src/database.js
@nocobase/database: Transform to cjs for src/index.js
@nocobase/database: Transform to cjs for src/model.js
@nocobase/database: Transform to cjs for src/op.js
@nocobase/database: Transform to cjs for src/table.js
@nocobase/database: Transform to cjs for src/utils.js
@nocobase/database: Transform to cjs for src/__tests__/index.js
@nocobase/database: Transform to cjs for src/fields/field-types.js
@nocobase/database: Transform to cjs for src/fields/index.js
@nocobase/database: Transform to cjs for src/fields/option-types.js
@nocobase/database: Transform to cjs for src/__tests__/model/getValuesByFieldNames.js
@nocobase/database: Transform to cjs for src/__tests__/tables/demos.js
@nocobase/database: Transform to cjs for src/__tests__/tables/extends.js
@nocobase/database: Transform to cjs for src/__tests__/tables/tests2.js
@nocobase/database: Transform to cjs for src/__tests__/utils/modules/fnts.js
@nocobase/database: Transform to cjs for src/__tests__/utils/modules/objts.js
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/mo-fang/nocobase/node_modules/father-build/node_modules/gulp-typescript/release/output.js:130:43)
    at /Users/mo-fang/nocobase/node_modules/father-build/node_modules/gulp-typescript/release/output.js:65:22
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (/Users/mo-fang/nocobase/node_modules/duplexify/index.js:191:15)
    at /Users/mo-fang/nocobase/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zhuyifang** [comment]
我的env配置如下：
########## NOCOBASE ENV ##########

# DATABASE

DB_DIALECT=mysql
DB_HOST=localhost
DB_PORT=8889
DB_DATABASE=nocobase
DB_USER=nocobase
DB_PASSWORD=nocobase
# set to 'on' to enable log
DB_LOG_SQL=

**Comment by zhuyifang** [comment]
node v12.22.3
npm 6.14.13

**Comment by zhuyifang** [comment]
使用 node v14.17.3 之后，build通过

**Comment by chenos** [comment]
删掉 yarn.lock 文件再重新 yarn install
