### ISSUE TITLE
yarn bootstrap 时报错了

### ISSUE THREAD

**Issue by susamChen** [nocobase/nocobase#81]
报错信息如下：
:my-nocobase-project apple$ yarn bootstrap
yarn run v1.22.10
warning ../package.json: No license field
$ lerna bootstrap --no-ci
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 18 packages
lerna info Installing external dependencies
lerna ERR! npm install --no-package-lock exited 1 in '@nocobase/server'
lerna ERR! npm install --no-package-lock stderr:
npm ERR! code 1
npm ERR! path /Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/packages/server/node_modules/libpq
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@5.1.1
npm ERR! gyp info using node@14.16.0 | darwin | x64
npm ERR! gyp info find Python using Python version 2.7.13 found at "/Users/apple/anaconda2/bin/python"
npm ERR! gyp info spawn /Users/apple/anaconda2/bin/python
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/packages/server/node_modules/libpq/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/apple/Library/Caches/node-gyp/14.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/apple/Library/Caches/node-gyp/14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/apple/Library/Caches/node-gyp/14.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/packages/server/node_modules/libpq',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pg_config: command not found
npm ERR! gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 19.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/apple/Documents/work/Grow Room/前端/my-nocobase-project/packages/server/node_modules/libpq
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v5.1.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2021-08-19T15_25_55_155Z-debug.log

lerna ERR! npm install --no-package-lock exited 1 in '@nocobase/server'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
如果是 MacOS 可能是 xcode-select 的问题，重新安装一下试试，可以搜 node-gyp xcode-select 查找相关教程
